//! Bulk operations for ContentHash entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateContentHashDto;
use crate::application::service::ContentHashService;
use crate::domain::entity::ContentHash;

/// Bulk operation handler for ContentHash entities.
///
/// Wraps `ContentHashService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ContentHashBulkService = GenericBulkService<ContentHash, CreateContentHashDto, ContentHashService>;

// <<< CUSTOM
// END CUSTOM
