//! Bulk operations for FileShare entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateFileShareDto;
use crate::application::service::FileShareService;
use crate::domain::entity::FileShare;

/// Bulk operation handler for FileShare entities.
///
/// Wraps `FileShareService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type FileShareBulkService = GenericBulkService<FileShare, CreateFileShareDto, FileShareService>;

// <<< CUSTOM
// END CUSTOM
