//! AccessLog DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AccessLog;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AccessAction;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AccessLog
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAccessLogDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub file_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bucket_id: Option<Uuid>,
    pub action: AccessAction,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub share_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_owner: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_shared: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_public: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub referer: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bytes_transferred: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub success: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub accessed_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AccessLog
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAccessLogDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub file_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bucket_id: Option<Uuid>,
    pub action: AccessAction,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub share_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_owner: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_shared: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_public: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub referer: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bytes_transferred: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub success: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub accessed_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AccessLog
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAccessLogDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bucket_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<AccessAction>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub share_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_owner: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_shared: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 45)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub referer: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes_transferred: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accessed_at: Option<DateTime<Utc>>,
}

impl PatchAccessLogDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.file_id.is_some() || self.bucket_id.is_some() || self.action.is_some() || self.user_id.is_some() || self.share_id.is_some() || self.is_owner.is_some() || self.is_shared.is_some() || self.is_public.is_some() || self.ip_address.is_some() || self.user_agent.is_some() || self.referer.is_some() || self.country_code.is_some() || self.city.is_some() || self.bytes_transferred.is_some() || self.duration_ms.is_some() || self.success.is_some() || self.error_message.is_some() || self.accessed_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AccessLog entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AccessLogResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub file_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bucket_id: Option<Uuid>,
    pub action: AccessAction,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub share_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_owner: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_shared: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_public: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub referer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes_transferred: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub accessed_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AccessLog entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AccessLogListResponseDto {
    /// List of items
    pub items: Vec<AccessLogResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AccessLogListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AccessLogResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AccessLogSummaryDto {
    pub id: Uuid,
    pub file_id: Uuid,
    pub bucket_id: Option<Uuid>,
    pub action: AccessAction,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AccessLog> for AccessLogResponseDto {
    fn from(entity: AccessLog) -> Self {
        Self {
            id: entity.id,
            file_id: entity.file_id,
            bucket_id: entity.bucket_id,
            action: entity.action,
            user_id: entity.user_id,
            share_id: entity.share_id,
            is_owner: entity.is_owner,
            is_shared: entity.is_shared,
            is_public: entity.is_public,
            ip_address: entity.ip_address,
            user_agent: entity.user_agent,
            referer: entity.referer,
            country_code: entity.country_code,
            city: entity.city,
            bytes_transferred: entity.bytes_transferred,
            duration_ms: entity.duration_ms,
            success: entity.success,
            error_message: entity.error_message,
            accessed_at: entity.accessed_at,
            metadata: entity.metadata,
        }
    }
}

impl From<AccessLog> for AccessLogSummaryDto {
    fn from(entity: AccessLog) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            file_id: entity.file_id,
            bucket_id: entity.bucket_id,
            action: entity.action,
            created_at,
        }
    }
}

impl From<CreateAccessLogDto> for AccessLog {
    fn from(dto: CreateAccessLogDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            file_id: dto.file_id,
            bucket_id: dto.bucket_id,
            action: dto.action,
            user_id: dto.user_id,
            share_id: dto.share_id,
            is_owner: dto.is_owner,
            is_shared: dto.is_shared,
            is_public: dto.is_public,
            ip_address: dto.ip_address,
            user_agent: dto.user_agent,
            referer: dto.referer,
            country_code: dto.country_code,
            city: dto.city,
            bytes_transferred: dto.bytes_transferred,
            duration_ms: dto.duration_ms,
            success: dto.success,
            error_message: dto.error_message,
            accessed_at: dto.accessed_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AccessLog> for AccessLogResponseDto {
    fn from(entity: &AccessLog) -> Self {
        Self {
            id: entity.id.clone(),
            file_id: entity.file_id.clone(),
            bucket_id: entity.bucket_id.clone(),
            action: entity.action.clone(),
            user_id: entity.user_id.clone(),
            share_id: entity.share_id.clone(),
            is_owner: entity.is_owner.clone(),
            is_shared: entity.is_shared.clone(),
            is_public: entity.is_public.clone(),
            ip_address: entity.ip_address.clone(),
            user_agent: entity.user_agent.clone(),
            referer: entity.referer.clone(),
            country_code: entity.country_code.clone(),
            city: entity.city.clone(),
            bytes_transferred: entity.bytes_transferred.clone(),
            duration_ms: entity.duration_ms.clone(),
            success: entity.success.clone(),
            error_message: entity.error_message.clone(),
            accessed_at: entity.accessed_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAccessLogDto> for AccessLog {
    fn from_create_dto(dto: CreateAccessLogDto) -> backbone_core::ServiceResult<Self> {
        Ok(AccessLog::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAccessLogDto> for AccessLog {
    fn apply_update(mut self, dto: UpdateAccessLogDto) -> backbone_core::ServiceResult<Self> {
        self.file_id = dto.file_id;
        self.bucket_id = dto.bucket_id;
        self.action = dto.action;
        self.user_id = dto.user_id;
        self.share_id = dto.share_id;
        self.is_owner = dto.is_owner;
        self.is_shared = dto.is_shared;
        self.is_public = dto.is_public;
        self.ip_address = dto.ip_address;
        self.user_agent = dto.user_agent;
        self.referer = dto.referer;
        self.country_code = dto.country_code;
        self.city = dto.city;
        self.bytes_transferred = dto.bytes_transferred;
        self.duration_ms = dto.duration_ms;
        self.success = dto.success;
        self.error_message = dto.error_message;
        self.accessed_at = dto.accessed_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AccessLog here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
