//! FileShare DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::FileShare;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SharePermission;
use crate::domain::entity::ShareStatus;
use crate::domain::entity::ShareType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new FileShare
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateFileShareDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub file_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub owner_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(min = 32), length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token: String,
    pub share_type: ShareType,
    pub permission: SharePermission,
    pub shared_with: Vec<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password_hash: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_downloads: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub download_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    pub share_status: ShareStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a FileShare
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateFileShareDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub file_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub owner_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(min = 32), length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token: String,
    pub share_type: ShareType,
    pub permission: SharePermission,
    pub shared_with: Vec<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password_hash: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_downloads: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub download_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    pub share_status: ShareStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a FileShare
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchFileShareDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(min = 32), length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub share_type: Option<ShareType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission: Option<SharePermission>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shared_with: Option<Vec<Uuid>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_downloads: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub share_status: Option<ShareStatus>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PatchFileShareDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.file_id.is_some() || self.owner_id.is_some() || self.token.is_some() || self.share_type.is_some() || self.permission.is_some() || self.shared_with.is_some() || self.password_hash.is_some() || self.max_downloads.is_some() || self.download_count.is_some() || self.expires_at.is_some() || self.share_status.is_some() || self.is_active.is_some() || self.revoked_at.is_some() || self.revoked_by.is_some() || self.message.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for FileShare entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FileShareResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub file_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub owner_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token: String,
    pub share_type: ShareType,
    pub permission: SharePermission,
    pub shared_with: Vec<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_downloads: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub download_count: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    pub share_status: ShareStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for FileShare entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FileShareListResponseDto {
    /// List of items
    pub items: Vec<FileShareResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl FileShareListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<FileShareResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FileShareSummaryDto {
    pub id: Uuid,
    pub file_id: Uuid,
    pub owner_id: Uuid,
    pub token: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<FileShare> for FileShareResponseDto {
    fn from(entity: FileShare) -> Self {
        Self {
            id: entity.id,
            file_id: entity.file_id,
            owner_id: entity.owner_id,
            token: entity.token,
            share_type: entity.share_type,
            permission: entity.permission,
            shared_with: entity.shared_with,
            password_hash: entity.password_hash,
            max_downloads: entity.max_downloads,
            download_count: entity.download_count,
            expires_at: entity.expires_at,
            share_status: entity.share_status,
            is_active: entity.is_active,
            revoked_at: entity.revoked_at,
            revoked_by: entity.revoked_by,
            message: entity.message,
            metadata: entity.metadata,
        }
    }
}

impl From<FileShare> for FileShareSummaryDto {
    fn from(entity: FileShare) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            file_id: entity.file_id,
            owner_id: entity.owner_id,
            token: entity.token,
            created_at,
        }
    }
}

impl From<CreateFileShareDto> for FileShare {
    fn from(dto: CreateFileShareDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            file_id: dto.file_id,
            owner_id: dto.owner_id,
            token: dto.token,
            share_type: dto.share_type,
            permission: dto.permission,
            shared_with: dto.shared_with,
            password_hash: dto.password_hash,
            max_downloads: dto.max_downloads,
            download_count: dto.download_count,
            expires_at: dto.expires_at,
            share_status: dto.share_status,
            is_active: dto.is_active,
            revoked_at: dto.revoked_at,
            revoked_by: dto.revoked_by,
            message: dto.message,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&FileShare> for FileShareResponseDto {
    fn from(entity: &FileShare) -> Self {
        Self {
            id: entity.id.clone(),
            file_id: entity.file_id.clone(),
            owner_id: entity.owner_id.clone(),
            token: entity.token.clone(),
            share_type: entity.share_type.clone(),
            permission: entity.permission.clone(),
            shared_with: entity.shared_with.clone(),
            password_hash: entity.password_hash.clone(),
            max_downloads: entity.max_downloads.clone(),
            download_count: entity.download_count.clone(),
            expires_at: entity.expires_at.clone(),
            share_status: entity.share_status.clone(),
            is_active: entity.is_active.clone(),
            revoked_at: entity.revoked_at.clone(),
            revoked_by: entity.revoked_by.clone(),
            message: entity.message.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateFileShareDto> for FileShare {
    fn from_create_dto(dto: CreateFileShareDto) -> backbone_core::ServiceResult<Self> {
        Ok(FileShare::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateFileShareDto> for FileShare {
    fn apply_update(mut self, dto: UpdateFileShareDto) -> backbone_core::ServiceResult<Self> {
        self.file_id = dto.file_id;
        self.owner_id = dto.owner_id;
        self.token = dto.token;
        self.share_type = dto.share_type;
        self.permission = dto.permission;
        self.shared_with = dto.shared_with;
        self.password_hash = dto.password_hash;
        self.max_downloads = dto.max_downloads;
        self.download_count = dto.download_count;
        self.expires_at = dto.expires_at;
        self.share_status = dto.share_status;
        self.is_active = dto.is_active;
        self.revoked_at = dto.revoked_at;
        self.revoked_by = dto.revoked_by;
        self.message = dto.message;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to FileShare here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
