//! FileShare GraphQL resolvers
//!
//! Auto-generated by backbone-schema. Do not edit manually.

use std::sync::Arc;
use async_graphql::*;

use crate::application::service::FileShareService;
use crate::domain::entity::*;

// =================================================================
// GraphQL Output Type
// =================================================================

/// FileShare GraphQL output type
#[derive(Debug, Clone, SimpleObject)]
#[graphql(name = "BucketFileShare")]
pub struct FileShareGql {
    pub id: String,
    pub file_id: String,
    pub owner_id: String,
    pub token: String,
    pub share_type: String,
    pub permission: String,
    pub shared_with: Vec<String>,
    pub max_downloads: Option<i32>,
    pub download_count: i32,
    pub expires_at: Option<String>,
    pub is_active: bool,
    pub revoked_at: Option<String>,
    pub revoked_by: Option<String>,
    pub message: Option<String>,
    pub metadata: async_graphql::Json<serde_json::Value>,
}

impl From<FileShare> for FileShareGql {
    fn from(e: FileShare) -> Self {
        Self {
            id: e.id.to_string(),
            file_id: e.file_id.to_string(),
            owner_id: e.owner_id.to_string(),
            token: e.token,
            share_type: e.share_type.to_string(),
            permission: e.permission.to_string(),
            shared_with: e.shared_with.iter().map(|v| v.to_string()).collect(),
            max_downloads: e.max_downloads,
            download_count: e.download_count,
            expires_at: e.expires_at.map(|v| v.to_rfc3339()),
            is_active: e.is_active,
            revoked_at: e.revoked_at.map(|v| v.to_rfc3339()),
            revoked_by: e.revoked_by.map(|v| v.to_string()),
            message: e.message,
            metadata: async_graphql::Json(e.metadata),
        }
    }
}

// =================================================================
// Paginated Response
// =================================================================

#[derive(Debug, SimpleObject)]
#[graphql(name = "BucketFileSharePaginatedResponse")]
pub struct FileSharePaginatedResponse {
    pub data: Vec<FileShareGql>,
    pub total: i64,
    pub page: i32,
    pub limit: i32,
    pub total_pages: i32,
}

// =================================================================
// Input Types
// =================================================================

/// Input for creating a FileShare
#[derive(Debug, InputObject)]
#[graphql(name = "BucketCreateFileShareInput")]
pub struct CreateFileShareInput {
    pub file_id: String,
    pub owner_id: String,
    pub token: String,
    pub share_type: String,
    pub permission: String,
    pub shared_with: Vec<String>,
    pub password_hash: Option<String>,
    pub max_downloads: Option<i32>,
    pub download_count: i32,
    pub expires_at: Option<String>,
    pub is_active: bool,
    pub revoked_at: Option<String>,
    pub revoked_by: Option<String>,
    pub message: Option<String>,
}

/// Input for updating a FileShare
///
/// All fields are optional. Only provided fields will be updated.
#[derive(Debug, InputObject)]
#[graphql(name = "BucketUpdateFileShareInput")]
pub struct UpdateFileShareInput {
    pub file_id: Option<String>,
    pub owner_id: Option<String>,
    pub token: Option<String>,
    pub share_type: Option<String>,
    pub permission: Option<String>,
    pub shared_with: Option<Vec<String>>,
    pub password_hash: Option<Option<String>>,
    pub max_downloads: Option<Option<i32>>,
    pub download_count: Option<i32>,
    pub expires_at: Option<Option<String>>,
    pub is_active: Option<bool>,
    pub revoked_at: Option<Option<String>>,
    pub revoked_by: Option<Option<String>>,
    pub message: Option<Option<String>>,
}

// =================================================================
// Query Resolvers
// =================================================================

#[derive(Default)]
pub struct FileShareQuery;

#[Object(name = "BucketFileShareQuery")]
impl FileShareQuery {
    /// List file_shares with pagination
    async fn bucket_file_shares(
        &self,
        ctx: &Context<'_>,
        #[graphql(default = 1)] page: i32,
        #[graphql(default = 20)] limit: i32,
    ) -> Result<FileSharePaginatedResponse> {
        let service = ctx.data::<Arc<FileShareService>>()?;
        let p = page.max(1) as u32;
        let l = limit.clamp(1, 100) as u32;
        let (items, total) = service.list(p, l, Default::default()).await
            .map_err(|e| Error::new(e.to_string()))?;

        let total_pages = if l == 0 { 0 } else { ((total as f64) / (l as f64)).ceil() as i32 };

        Ok(FileSharePaginatedResponse {
            data: items.into_iter().map(Into::into).collect(),
            total: total as i64,
            page: p as i32,
            limit: l as i32,
            total_pages,
        })
    }

    /// Get file_share by ID
    async fn bucket_file_share(&self, ctx: &Context<'_>, id: String) -> Result<Option<FileShareGql>> {
        let service = ctx.data::<Arc<FileShareService>>()?;
        let entity = service.find_by_id(&id).await
            .map_err(|e| Error::new(e.to_string()))?;
        Ok(entity.map(Into::into))
    }
}

// =================================================================
// Mutation Resolvers
// =================================================================

#[derive(Default)]
pub struct FileShareMutation;

#[Object(name = "BucketFileShareMutation")]
impl FileShareMutation {
    /// Create a new file_share
    async fn bucket_create_file_share(
        &self,
        ctx: &Context<'_>,
        input: CreateFileShareInput,
    ) -> Result<FileShareGql> {
        let service = ctx.data::<Arc<FileShareService>>()?;

        let entity = FileShare {
            id: uuid::Uuid::new_v4(),
            file_id: input.file_id.parse::<uuid::Uuid>()
                .map_err(|e| Error::new(format!("Invalid file_id: {}", e)))?,
            owner_id: input.owner_id.parse::<uuid::Uuid>()
                .map_err(|e| Error::new(format!("Invalid owner_id: {}", e)))?,
            token: input.token,
            share_type: input.share_type.parse::<ShareType>()
                .map_err(|e| Error::new(format!("Invalid share_type: {}", e)))?,
            permission: input.permission.parse::<SharePermission>()
                .map_err(|e| Error::new(format!("Invalid permission: {}", e)))?,
            shared_with: input.shared_with.into_iter().map(|v| v.parse::<uuid::Uuid>()).collect::<Result<Vec<_>, _>>()
                .map_err(|e| Error::new(format!("Invalid shared_with: {}", e)))?,
            password_hash: input.password_hash,
            max_downloads: input.max_downloads,
            download_count: input.download_count,
            expires_at: input.expires_at.map(|v| v.parse::<chrono::DateTime<chrono::Utc>>()).transpose()
                .map_err(|e| Error::new(format!("Invalid expires_at: {}", e)))?,
            is_active: input.is_active,
            revoked_at: input.revoked_at.map(|v| v.parse::<chrono::DateTime<chrono::Utc>>()).transpose()
                .map_err(|e| Error::new(format!("Invalid revoked_at: {}", e)))?,
            revoked_by: input.revoked_by.map(|v| v.parse::<uuid::Uuid>()).transpose()
                .map_err(|e| Error::new(format!("Invalid revoked_by: {}", e)))?,
            message: input.message,
            metadata: Default::default(),
        };

        let created = service.create(entity).await
            .map_err(|e| Error::new(e.to_string()))?;
        Ok(created.into())
    }

    /// Update file_share by ID
    async fn bucket_update_file_share(
        &self,
        ctx: &Context<'_>,
        id: String,
        input: UpdateFileShareInput,
    ) -> Result<FileShareGql> {
        let service = ctx.data::<Arc<FileShareService>>()?;
        let mut entity = service.find_by_id(&id).await
            .map_err(|e| Error::new(e.to_string()))?
            .ok_or_else(|| Error::new(format!("FileShare not found: {}", id)))?;

        if let Some(val) = input.file_id { entity.file_id = val.parse::<uuid::Uuid>()
            .map_err(|e| Error::new(format!("Invalid file_id: {}", e)))?; }
        if let Some(val) = input.owner_id { entity.owner_id = val.parse::<uuid::Uuid>()
            .map_err(|e| Error::new(format!("Invalid owner_id: {}", e)))?; }
        if let Some(val) = input.token { entity.token = val; }
        if let Some(val) = input.share_type { entity.share_type = val.parse::<ShareType>()
            .map_err(|e| Error::new(format!("Invalid share_type: {}", e)))?; }
        if let Some(val) = input.permission { entity.permission = val.parse::<SharePermission>()
            .map_err(|e| Error::new(format!("Invalid permission: {}", e)))?; }
        if let Some(val) = input.shared_with { entity.shared_with = val.into_iter().map(|v| v.parse::<uuid::Uuid>()).collect::<Result<Vec<_>, _>>()
            .map_err(|e| Error::new(format!("Invalid shared_with: {}", e)))?; }
        if let Some(val) = input.password_hash { entity.password_hash = val; }
        if let Some(val) = input.max_downloads { entity.max_downloads = val; }
        if let Some(val) = input.download_count { entity.download_count = val; }
        if let Some(val) = input.expires_at { entity.expires_at = val.map(|v| v.parse::<chrono::DateTime<chrono::Utc>>()).transpose()
            .map_err(|e| Error::new(format!("Invalid expires_at: {}", e)))?; }
        if let Some(val) = input.is_active { entity.is_active = val; }
        if let Some(val) = input.revoked_at { entity.revoked_at = val.map(|v| v.parse::<chrono::DateTime<chrono::Utc>>()).transpose()
            .map_err(|e| Error::new(format!("Invalid revoked_at: {}", e)))?; }
        if let Some(val) = input.revoked_by { entity.revoked_by = val.map(|v| v.parse::<uuid::Uuid>()).transpose()
            .map_err(|e| Error::new(format!("Invalid revoked_by: {}", e)))?; }
        if let Some(val) = input.message { entity.message = val; }

        let updated = service.update(&id, entity).await
            .map_err(|e| Error::new(e.to_string()))?
            .ok_or_else(|| Error::new(format!("FileShare not found: {}", id)))?;
        Ok(updated.into())
    }

    /// Delete file_share (soft delete)
    async fn bucket_delete_file_share(&self, ctx: &Context<'_>, id: String) -> Result<bool> {
        let service = ctx.data::<Arc<FileShareService>>()?;
        service.delete(&id).await
            .map_err(|e| Error::new(e.to_string()))
    }
}
