//! Thumbnail GraphQL resolvers
//!
//! Auto-generated by backbone-schema. Do not edit manually.

use std::sync::Arc;
use async_graphql::*;

use crate::application::service::ThumbnailService;
use crate::domain::entity::*;

// =================================================================
// GraphQL Output Type
// =================================================================

/// Thumbnail GraphQL output type
#[derive(Debug, Clone, SimpleObject)]
#[graphql(name = "BucketThumbnail")]
pub struct ThumbnailGql {
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub id: String,
    pub file_id: String,
    pub size: String,
    pub width: i32,
    pub height: i32,
    pub storage_key: String,
    pub storage_backend: String,
    pub mime_type: String,
    pub format: String,
    pub quality: i32,
    pub size_bytes: i64,
    pub generated_at: String,
    pub generation_time_ms: i32,
    pub source_version: i32,
    pub cdn_url: String,
    pub cache_expires_at: String,
    pub is_stale: bool,
}

impl From<Thumbnail> for ThumbnailGql {
    fn from(e: Thumbnail) -> Self {
        Self {
            created_at: e.created_at.to_rfc3339(),
            updated_at: e.updated_at.to_rfc3339(),
            deleted_at: e.deleted_at.map(|v| v.to_rfc3339()),
            id: e.id.to_string(),
            file_id: e.file_id.to_string(),
            size: e.size.to_string(),
            width: e.width,
            height: e.height,
            storage_key: e.storage_key,
            storage_backend: e.storage_backend,
            mime_type: e.mime_type,
            format: e.format,
            quality: e.quality,
            size_bytes: e.size_bytes,
            generated_at: e.generated_at.to_rfc3339(),
            generation_time_ms: e.generation_time_ms,
            source_version: e.source_version,
            cdn_url: e.cdn_url,
            cache_expires_at: e.cache_expires_at.to_rfc3339(),
            is_stale: e.is_stale,
        }
    }
}

// =================================================================
// Paginated Response
// =================================================================

#[derive(Debug, SimpleObject)]
#[graphql(name = "BucketThumbnailPaginatedResponse")]
pub struct ThumbnailPaginatedResponse {
    pub data: Vec<ThumbnailGql>,
    pub total: i64,
    pub page: i32,
    pub limit: i32,
    pub total_pages: i32,
}

// =================================================================
// Input Types
// =================================================================

/// Input for creating a Thumbnail
#[derive(Debug, InputObject)]
#[graphql(name = "BucketCreateThumbnailInput")]
pub struct CreateThumbnailInput {
    pub file_id: String,
    pub size: String,
    pub width: i32,
    pub height: i32,
    pub storage_key: String,
    pub storage_backend: String,
    pub mime_type: String,
    pub format: String,
    pub quality: i32,
    pub size_bytes: i64,
    pub generated_at: String,
    pub generation_time_ms: i32,
    pub source_version: i32,
    pub cdn_url: String,
    pub cache_expires_at: String,
    pub is_stale: bool,
}

/// Input for updating a Thumbnail
///
/// All fields are optional. Only provided fields will be updated.
#[derive(Debug, InputObject)]
#[graphql(name = "BucketUpdateThumbnailInput")]
pub struct UpdateThumbnailInput {
    pub file_id: Option<String>,
    pub size: Option<String>,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub storage_key: Option<String>,
    pub storage_backend: Option<String>,
    pub mime_type: Option<String>,
    pub format: Option<String>,
    pub quality: Option<i32>,
    pub size_bytes: Option<i64>,
    pub generated_at: Option<String>,
    pub generation_time_ms: Option<i32>,
    pub source_version: Option<i32>,
    pub cdn_url: Option<String>,
    pub cache_expires_at: Option<String>,
    pub is_stale: Option<bool>,
}

// =================================================================
// Query Resolvers
// =================================================================

#[derive(Default)]
pub struct ThumbnailQuery;

#[Object(name = "BucketThumbnailQuery")]
impl ThumbnailQuery {
    /// List thumbnails with pagination
    async fn bucket_thumbnails(
        &self,
        ctx: &Context<'_>,
        #[graphql(default = 1)] page: i32,
        #[graphql(default = 20)] limit: i32,
    ) -> Result<ThumbnailPaginatedResponse> {
        let service = ctx.data::<Arc<ThumbnailService>>()?;
        let p = page.max(1) as u32;
        let l = limit.clamp(1, 100) as u32;
        let (items, total) = service.list(p, l, Default::default()).await
            .map_err(|e| Error::new(e.to_string()))?;

        let total_pages = if l == 0 { 0 } else { ((total as f64) / (l as f64)).ceil() as i32 };

        Ok(ThumbnailPaginatedResponse {
            data: items.into_iter().map(Into::into).collect(),
            total: total as i64,
            page: p as i32,
            limit: l as i32,
            total_pages,
        })
    }

    /// Get thumbnail by ID
    async fn bucket_thumbnail(&self, ctx: &Context<'_>, id: String) -> Result<Option<ThumbnailGql>> {
        let service = ctx.data::<Arc<ThumbnailService>>()?;
        let entity = service.find_by_id(&id).await
            .map_err(|e| Error::new(e.to_string()))?;
        Ok(entity.map(Into::into))
    }
}

// =================================================================
// Mutation Resolvers
// =================================================================

#[derive(Default)]
pub struct ThumbnailMutation;

#[Object(name = "BucketThumbnailMutation")]
impl ThumbnailMutation {
    /// Create a new thumbnail
    async fn bucket_create_thumbnail(
        &self,
        ctx: &Context<'_>,
        input: CreateThumbnailInput,
    ) -> Result<ThumbnailGql> {
        let service = ctx.data::<Arc<ThumbnailService>>()?;

        let entity = Thumbnail {
            created_at: chrono::Utc::now(),
            updated_at: chrono::Utc::now(),
            deleted_at: None,
            id: uuid::Uuid::new_v4(),
            file_id: input.file_id.parse::<uuid::Uuid>()
                .map_err(|e| Error::new(format!("Invalid file_id: {}", e)))?,
            size: input.size.parse::<ThumbnailSize>()
                .map_err(|e| Error::new(format!("Invalid size: {}", e)))?,
            width: input.width,
            height: input.height,
            storage_key: input.storage_key,
            storage_backend: input.storage_backend,
            mime_type: input.mime_type,
            format: input.format,
            quality: input.quality,
            size_bytes: input.size_bytes,
            generated_at: input.generated_at.parse::<chrono::DateTime<chrono::Utc>>()
                .map_err(|e| Error::new(format!("Invalid generated_at: {}", e)))?,
            generation_time_ms: input.generation_time_ms,
            source_version: input.source_version,
            cdn_url: input.cdn_url,
            cache_expires_at: input.cache_expires_at.parse::<chrono::DateTime<chrono::Utc>>()
                .map_err(|e| Error::new(format!("Invalid cache_expires_at: {}", e)))?,
            is_stale: input.is_stale,
        };

        let created = service.create(entity).await
            .map_err(|e| Error::new(e.to_string()))?;
        Ok(created.into())
    }

    /// Update thumbnail by ID
    async fn bucket_update_thumbnail(
        &self,
        ctx: &Context<'_>,
        id: String,
        input: UpdateThumbnailInput,
    ) -> Result<ThumbnailGql> {
        let service = ctx.data::<Arc<ThumbnailService>>()?;
        let mut entity = service.find_by_id(&id).await
            .map_err(|e| Error::new(e.to_string()))?
            .ok_or_else(|| Error::new(format!("Thumbnail not found: {}", id)))?;

        if let Some(val) = input.file_id { entity.file_id = val.parse::<uuid::Uuid>()
            .map_err(|e| Error::new(format!("Invalid file_id: {}", e)))?; }
        if let Some(val) = input.size { entity.size = val.parse::<ThumbnailSize>()
            .map_err(|e| Error::new(format!("Invalid size: {}", e)))?; }
        if let Some(val) = input.width { entity.width = val; }
        if let Some(val) = input.height { entity.height = val; }
        if let Some(val) = input.storage_key { entity.storage_key = val; }
        if let Some(val) = input.storage_backend { entity.storage_backend = val; }
        if let Some(val) = input.mime_type { entity.mime_type = val; }
        if let Some(val) = input.format { entity.format = val; }
        if let Some(val) = input.quality { entity.quality = val; }
        if let Some(val) = input.size_bytes { entity.size_bytes = val; }
        if let Some(val) = input.generated_at { entity.generated_at = val.parse::<chrono::DateTime<chrono::Utc>>()
            .map_err(|e| Error::new(format!("Invalid generated_at: {}", e)))?; }
        if let Some(val) = input.generation_time_ms { entity.generation_time_ms = val; }
        if let Some(val) = input.source_version { entity.source_version = val; }
        if let Some(val) = input.cdn_url { entity.cdn_url = val; }
        if let Some(val) = input.cache_expires_at { entity.cache_expires_at = val.parse::<chrono::DateTime<chrono::Utc>>()
            .map_err(|e| Error::new(format!("Invalid cache_expires_at: {}", e)))?; }
        if let Some(val) = input.is_stale { entity.is_stale = val; }

        let updated = service.update(&id, entity).await
            .map_err(|e| Error::new(e.to_string()))?
            .ok_or_else(|| Error::new(format!("Thumbnail not found: {}", id)))?;
        Ok(updated.into())
    }

    /// Delete thumbnail (soft delete)
    async fn bucket_delete_thumbnail(&self, ctx: &Context<'_>, id: String) -> Result<bool> {
        let service = ctx.data::<Arc<ThumbnailService>>()?;
        service.delete(&id).await
            .map_err(|e| Error::new(e.to_string()))
    }
}
