//! UploadSession GraphQL resolvers
//!
//! Auto-generated by backbone-schema. Do not edit manually.

use std::sync::Arc;
use async_graphql::*;

use crate::application::service::UploadSessionService;
use crate::domain::entity::*;

// =================================================================
// GraphQL Output Type
// =================================================================

/// UploadSession GraphQL output type
#[derive(Debug, Clone, SimpleObject)]
#[graphql(name = "BucketUploadSession")]
pub struct UploadSessionGql {
    pub id: String,
    pub bucket_id: String,
    pub user_id: String,
    pub path: String,
    pub filename: String,
    pub mime_type: Option<String>,
    pub file_size: i64,
    pub chunk_size: i32,
    pub total_chunks: i32,
    pub uploaded_chunks: i32,
    pub status: String,
    pub storage_backend: String,
    pub completed_parts: Vec<i32>,
    pub part_etags: Option<async_graphql::Json<serde_json::Value>>,
    pub expires_at: String,
    pub metadata: Option<async_graphql::Json<serde_json::Value>>,
}

impl From<UploadSession> for UploadSessionGql {
    fn from(e: UploadSession) -> Self {
        Self {
            id: e.id.to_string(),
            bucket_id: e.bucket_id.to_string(),
            user_id: e.user_id.to_string(),
            path: e.path,
            filename: e.filename,
            mime_type: e.mime_type,
            file_size: e.file_size,
            chunk_size: e.chunk_size,
            total_chunks: e.total_chunks,
            uploaded_chunks: e.uploaded_chunks,
            status: e.status.to_string(),
            storage_backend: e.storage_backend.to_string(),
            completed_parts: e.completed_parts.clone(),
            part_etags: e.part_etags.map(|v| async_graphql::Json(v)),
            expires_at: e.expires_at.to_rfc3339(),
            metadata: e.metadata.map(|v| async_graphql::Json(v)),
        }
    }
}

// =================================================================
// Paginated Response
// =================================================================

#[derive(Debug, SimpleObject)]
#[graphql(name = "BucketUploadSessionPaginatedResponse")]
pub struct UploadSessionPaginatedResponse {
    pub data: Vec<UploadSessionGql>,
    pub total: i64,
    pub page: i32,
    pub limit: i32,
    pub total_pages: i32,
}

// =================================================================
// Input Types
// =================================================================

/// Input for creating a UploadSession
#[derive(Debug, InputObject)]
#[graphql(name = "BucketCreateUploadSessionInput")]
pub struct CreateUploadSessionInput {
    pub bucket_id: String,
    pub user_id: String,
    pub path: String,
    pub filename: String,
    pub mime_type: Option<String>,
    pub file_size: i64,
    pub chunk_size: i32,
    pub total_chunks: i32,
    pub uploaded_chunks: i32,
    pub status: String,
    pub storage_backend: String,
    pub completed_parts: Vec<i32>,
    pub part_etags: Option<async_graphql::Json<serde_json::Value>>,
    pub expires_at: String,
}

/// Input for updating a UploadSession
///
/// All fields are optional. Only provided fields will be updated.
#[derive(Debug, InputObject)]
#[graphql(name = "BucketUpdateUploadSessionInput")]
pub struct UpdateUploadSessionInput {
    pub bucket_id: Option<String>,
    pub user_id: Option<String>,
    pub path: Option<String>,
    pub filename: Option<String>,
    pub mime_type: Option<Option<String>>,
    pub file_size: Option<i64>,
    pub chunk_size: Option<i32>,
    pub total_chunks: Option<i32>,
    pub uploaded_chunks: Option<i32>,
    pub status: Option<String>,
    pub storage_backend: Option<String>,
    pub completed_parts: Option<Vec<i32>>,
    pub part_etags: Option<Option<async_graphql::Json<serde_json::Value>>>,
    pub expires_at: Option<String>,
}

// =================================================================
// Query Resolvers
// =================================================================

#[derive(Default)]
pub struct UploadSessionQuery;

#[Object(name = "BucketUploadSessionQuery")]
impl UploadSessionQuery {
    /// List upload_sessions with pagination
    async fn bucket_upload_sessions(
        &self,
        ctx: &Context<'_>,
        #[graphql(default = 1)] page: i32,
        #[graphql(default = 20)] limit: i32,
    ) -> Result<UploadSessionPaginatedResponse> {
        let service = ctx.data::<Arc<UploadSessionService>>()?;
        let p = page.max(1) as u32;
        let l = limit.clamp(1, 100) as u32;
        let (items, total) = service.list(p, l, Default::default()).await
            .map_err(|e| Error::new(e.to_string()))?;

        let total_pages = if l == 0 { 0 } else { ((total as f64) / (l as f64)).ceil() as i32 };

        Ok(UploadSessionPaginatedResponse {
            data: items.into_iter().map(Into::into).collect(),
            total: total as i64,
            page: p as i32,
            limit: l as i32,
            total_pages,
        })
    }

    /// Get upload_session by ID
    async fn bucket_upload_session(&self, ctx: &Context<'_>, id: String) -> Result<Option<UploadSessionGql>> {
        let service = ctx.data::<Arc<UploadSessionService>>()?;
        let entity = service.find_by_id(&id).await
            .map_err(|e| Error::new(e.to_string()))?;
        Ok(entity.map(Into::into))
    }
}

// =================================================================
// Mutation Resolvers
// =================================================================

#[derive(Default)]
pub struct UploadSessionMutation;

#[Object(name = "BucketUploadSessionMutation")]
impl UploadSessionMutation {
    /// Create a new upload_session
    async fn bucket_create_upload_session(
        &self,
        ctx: &Context<'_>,
        input: CreateUploadSessionInput,
    ) -> Result<UploadSessionGql> {
        let service = ctx.data::<Arc<UploadSessionService>>()?;

        let entity = UploadSession {
            id: uuid::Uuid::new_v4(),
            bucket_id: input.bucket_id.parse::<uuid::Uuid>()
                .map_err(|e| Error::new(format!("Invalid bucket_id: {}", e)))?,
            user_id: input.user_id.parse::<uuid::Uuid>()
                .map_err(|e| Error::new(format!("Invalid user_id: {}", e)))?,
            path: input.path,
            filename: input.filename,
            mime_type: input.mime_type,
            file_size: input.file_size,
            chunk_size: input.chunk_size,
            total_chunks: input.total_chunks,
            uploaded_chunks: input.uploaded_chunks,
            status: input.status.parse::<UploadStatus>()
                .map_err(|e| Error::new(format!("Invalid status: {}", e)))?,
            storage_backend: input.storage_backend.parse::<StorageBackend>()
                .map_err(|e| Error::new(format!("Invalid storage_backend: {}", e)))?,
            completed_parts: input.completed_parts.into_iter().map(|v| v).collect(),
            part_etags: input.part_etags.map(|v| v.0),
            expires_at: input.expires_at.parse::<chrono::DateTime<chrono::Utc>>()
                .map_err(|e| Error::new(format!("Invalid expires_at: {}", e)))?,
            metadata: None,
        };

        let created = service.create(entity).await
            .map_err(|e| Error::new(e.to_string()))?;
        Ok(created.into())
    }

    /// Update upload_session by ID
    async fn bucket_update_upload_session(
        &self,
        ctx: &Context<'_>,
        id: String,
        input: UpdateUploadSessionInput,
    ) -> Result<UploadSessionGql> {
        let service = ctx.data::<Arc<UploadSessionService>>()?;
        let mut entity = service.find_by_id(&id).await
            .map_err(|e| Error::new(e.to_string()))?
            .ok_or_else(|| Error::new(format!("UploadSession not found: {}", id)))?;

        if let Some(val) = input.bucket_id { entity.bucket_id = val.parse::<uuid::Uuid>()
            .map_err(|e| Error::new(format!("Invalid bucket_id: {}", e)))?; }
        if let Some(val) = input.user_id { entity.user_id = val.parse::<uuid::Uuid>()
            .map_err(|e| Error::new(format!("Invalid user_id: {}", e)))?; }
        if let Some(val) = input.path { entity.path = val; }
        if let Some(val) = input.filename { entity.filename = val; }
        if let Some(val) = input.mime_type { entity.mime_type = val; }
        if let Some(val) = input.file_size { entity.file_size = val; }
        if let Some(val) = input.chunk_size { entity.chunk_size = val; }
        if let Some(val) = input.total_chunks { entity.total_chunks = val; }
        if let Some(val) = input.uploaded_chunks { entity.uploaded_chunks = val; }
        if let Some(val) = input.status { entity.status = val.parse::<UploadStatus>()
            .map_err(|e| Error::new(format!("Invalid status: {}", e)))?; }
        if let Some(val) = input.storage_backend { entity.storage_backend = val.parse::<StorageBackend>()
            .map_err(|e| Error::new(format!("Invalid storage_backend: {}", e)))?; }
        if let Some(val) = input.completed_parts { entity.completed_parts = val.into_iter().map(|v| v).collect(); }
        if let Some(val) = input.part_etags { entity.part_etags = val.map(|v| v.0); }
        if let Some(val) = input.expires_at { entity.expires_at = val.parse::<chrono::DateTime<chrono::Utc>>()
            .map_err(|e| Error::new(format!("Invalid expires_at: {}", e)))?; }

        let updated = service.update(&id, entity).await
            .map_err(|e| Error::new(e.to_string()))?
            .ok_or_else(|| Error::new(format!("UploadSession not found: {}", id)))?;
        Ok(updated.into())
    }

    /// Delete upload_session (soft delete)
    async fn bucket_delete_upload_session(&self, ctx: &Context<'_>, id: String) -> Result<bool> {
        let service = ctx.data::<Arc<UploadSessionService>>()?;
        service.delete(&id).await
            .map_err(|e| Error::new(e.to_string()))
    }
}
