//! AccessLog gRPC service implementation
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use tonic::{Request, Response, Status};
use uuid::Uuid;

use crate::domain::entity::AccessLog;
use crate::infrastructure::persistence::access_log_repository::AccessLogRepository;

// Generated protobuf types
use crate::proto::access_log_v1::{
    access_log_service_server::access_logService,
    AccessLog as ProtoAccessLog,
    ListAccessLogRequest, ListAccessLogResponse,
    CreateAccessLogRequest,
    GetAccessLogRequest,
    UpdateAccessLogRequest,
    PatchAccessLogRequest,
    DeleteAccessLogRequest,
    BulkCreateAccessLogRequest, BulkCreateAccessLogResponse,
    UpsertAccessLogRequest,
    ListAccessLogTrashRequest,
    RestoreAccessLogRequest,
    EmptyAccessLogTrashRequest, EmptyAccessLogTrashResponse,
    // Streaming types
    StreamAccessLogRequest,
    SyncAccessLogRequest, SyncAccessLogResponse, SyncError,
    WatchAccessLogRequest, AccessLogEvent,
};

// Streaming imports
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tonic::Streaming;
use futures::StreamExt;

/// AccessLog gRPC service implementation
pub struct AccessLogGrpcService {
    repository: Arc<AccessLogRepository>,
}

impl AccessLogGrpcService {
    pub fn new(repository: Arc<AccessLogRepository>) -> Self {
        Self { repository }
    }
}

impl From<AccessLog> for ProtoAccessLog {
    fn from(entity: AccessLog) -> Self {
        Self {
            id: entity.id,
            file_id: entity.file_id,
            bucket_id: entity.bucket_id,
            action: entity.action,
            user_id: entity.user_id,
            share_id: entity.share_id,
            is_owner: entity.is_owner,
            is_shared: entity.is_shared,
            is_public: entity.is_public,
            ip_address: entity.ip_address,
            user_agent: entity.user_agent,
            referer: entity.referer,
            country_code: entity.country_code,
            city: entity.city,
            bytes_transferred: entity.bytes_transferred,
            duration_ms: entity.duration_ms,
            success: entity.success,
            error_message: entity.error_message,
            accessed_at: entity.accessed_at,
            metadata: entity.metadata,
        }
    }
}

#[tonic::async_trait]
impl access_logService for AccessLogGrpcService {
    async fn list(
        &self,
        request: Request<ListAccessLogRequest>,
    ) -> Result<Response<ListAccessLogResponse>, Status> {
        let req = request.into_inner();
        
        let page = if req.page > 0 { req.page } else { 1 };
        let per_page = if req.per_page > 0 { req.per_page } else { 20 };
        let sort_by = if req.sort_by.is_empty() { None } else { Some(req.sort_by.as_str()) };
        let sort_order = if req.sort_order.is_empty() { None } else { Some(req.sort_order.as_str()) };
        
        let (items, total) = self.repository
            .list(page, per_page, sort_by, sort_order)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        let total_pages = ((total as f64) / (per_page as f64)).ceil() as i32;
        
        Ok(Response::new(ListAccessLogResponse {
            items: items.into_iter().map(Into::into).collect(),
            total: total as i64,
            page,
            per_page,
            total_pages,
        }))
    }

    async fn create(
        &self,
        request: Request<CreateAccessLogRequest>,
    ) -> Result<Response<ProtoAccessLog>, Status> {
        let req = request.into_inner();
        
        let entity = AccessLog {
            id: Uuid::new_v4().to_string(),
            file_id: req.file_id,
            bucket_id: req.bucket_id,
            action: req.action,
            user_id: req.user_id,
            share_id: req.share_id,
            is_owner: req.is_owner,
            is_shared: req.is_shared,
            is_public: req.is_public,
            ip_address: req.ip_address,
            user_agent: req.user_agent,
            referer: req.referer,
            country_code: req.country_code,
            city: req.city,
            bytes_transferred: req.bytes_transferred,
            duration_ms: req.duration_ms,
            success: req.success,
            error_message: req.error_message,
            accessed_at: req.accessed_at,
            metadata: req.metadata,
        };
        
        let created = self.repository
            .create(entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(created.into()))
    }

    async fn get(
        &self,
        request: Request<GetAccessLogRequest>,
    ) -> Result<Response<ProtoAccessLog>, Status> {
        let req = request.into_inner();
        
        let entity = self.repository
            .find_by_id(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("AccessLog not found: {}", req.id)))?;
        
        Ok(Response::new(entity.into()))
    }

    async fn update(
        &self,
        request: Request<UpdateAccessLogRequest>,
    ) -> Result<Response<ProtoAccessLog>, Status> {
        let req = request.into_inner();
        
        let existing = self.repository
            .find_by_id(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("AccessLog not found: {}", req.id)))?;
        
        let entity = AccessLog {
            id: existing.id,
            file_id: req.file_id,
            bucket_id: req.bucket_id,
            action: req.action,
            user_id: req.user_id,
            share_id: req.share_id,
            is_owner: req.is_owner,
            is_shared: req.is_shared,
            is_public: req.is_public,
            ip_address: req.ip_address,
            user_agent: req.user_agent,
            referer: req.referer,
            country_code: req.country_code,
            city: req.city,
            bytes_transferred: req.bytes_transferred,
            duration_ms: req.duration_ms,
            success: req.success,
            error_message: req.error_message,
            accessed_at: req.accessed_at,
            metadata: req.metadata,
        };
        
        let updated = self.repository
            .update(&req.id, entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(updated.into()))
    }

    async fn patch(
        &self,
        request: Request<PatchAccessLogRequest>,
    ) -> Result<Response<ProtoAccessLog>, Status> {
        let req = request.into_inner();
        
        let mut existing = self.repository
            .find_by_id(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("AccessLog not found: {}", req.id)))?;
        
        if let Some(value) = req.file_id {
            existing.file_id = value;
        }
        if let Some(value) = req.bucket_id {
            existing.bucket_id = value;
        }
        if let Some(value) = req.action {
            existing.action = value;
        }
        if let Some(value) = req.user_id {
            existing.user_id = value;
        }
        if let Some(value) = req.share_id {
            existing.share_id = value;
        }
        if let Some(value) = req.is_owner {
            existing.is_owner = value;
        }
        if let Some(value) = req.is_shared {
            existing.is_shared = value;
        }
        if let Some(value) = req.is_public {
            existing.is_public = value;
        }
        if let Some(value) = req.ip_address {
            existing.ip_address = value;
        }
        if let Some(value) = req.user_agent {
            existing.user_agent = value;
        }
        if let Some(value) = req.referer {
            existing.referer = value;
        }
        if let Some(value) = req.country_code {
            existing.country_code = value;
        }
        if let Some(value) = req.city {
            existing.city = value;
        }
        if let Some(value) = req.bytes_transferred {
            existing.bytes_transferred = value;
        }
        if let Some(value) = req.duration_ms {
            existing.duration_ms = value;
        }
        if let Some(value) = req.success {
            existing.success = value;
        }
        if let Some(value) = req.error_message {
            existing.error_message = value;
        }
        if let Some(value) = req.accessed_at {
            existing.accessed_at = value;
        }
        if let Some(value) = req.metadata {
            existing.metadata = value;
        }
        existing.updated_at = chrono::Utc::now();
        
        let updated = self.repository
            .update(&req.id, existing)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(updated.into()))
    }

    async fn delete(
        &self,
        request: Request<DeleteAccessLogRequest>,
    ) -> Result<Response<()>, Status> {
        let req = request.into_inner();
        
        self.repository
            .soft_delete(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(()))
    }

    async fn bulk_create(
        &self,
        request: Request<BulkCreateAccessLogRequest>,
    ) -> Result<Response<BulkCreateAccessLogResponse>, Status> {
        let req = request.into_inner();
        
        let entities: Vec<AccessLog> = req.items
            .into_iter()
            .map(|item| AccessLog {
                id: Uuid::new_v4().to_string(),
                file_id: item.file_id,
                bucket_id: item.bucket_id,
                action: item.action,
                user_id: item.user_id,
                share_id: item.share_id,
                is_owner: item.is_owner,
                is_shared: item.is_shared,
                is_public: item.is_public,
                ip_address: item.ip_address,
                user_agent: item.user_agent,
                referer: item.referer,
                country_code: item.country_code,
                city: item.city,
                bytes_transferred: item.bytes_transferred,
                duration_ms: item.duration_ms,
                success: item.success,
                error_message: item.error_message,
                accessed_at: item.accessed_at,
                metadata: item.metadata,
            })
            .collect();
        
        let count = entities.len() as i32;
        let created = self.repository
            .bulk_create(entities)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(BulkCreateAccessLogResponse {
            items: created.into_iter().map(Into::into).collect(),
            created_count: count,
        }))
    }

    async fn upsert(
        &self,
        request: Request<UpsertAccessLogRequest>,
    ) -> Result<Response<ProtoAccessLog>, Status> {
        let req = request.into_inner();
        
        let key_field = if req.key_field.is_empty() { "id" } else { &req.key_field };
        let existing = self.repository
            .find_by_field(key_field, &req.key_value)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        let entity = match existing {
            Some(mut e) => {
                e.file_id = req.file_id;
                e.bucket_id = req.bucket_id;
                e.action = req.action;
                e.user_id = req.user_id;
                e.share_id = req.share_id;
                e.is_owner = req.is_owner;
                e.is_shared = req.is_shared;
                e.is_public = req.is_public;
                e.ip_address = req.ip_address;
                e.user_agent = req.user_agent;
                e.referer = req.referer;
                e.country_code = req.country_code;
                e.city = req.city;
                e.bytes_transferred = req.bytes_transferred;
                e.duration_ms = req.duration_ms;
                e.success = req.success;
                e.error_message = req.error_message;
                e.accessed_at = req.accessed_at;
                e.metadata = req.metadata;
                e
            }
            None => {
                AccessLog {
                    id: Uuid::new_v4().to_string(),
                    file_id: req.file_id,
                    bucket_id: req.bucket_id,
                    action: req.action,
                    user_id: req.user_id,
                    share_id: req.share_id,
                    is_owner: req.is_owner,
                    is_shared: req.is_shared,
                    is_public: req.is_public,
                    ip_address: req.ip_address,
                    user_agent: req.user_agent,
                    referer: req.referer,
                    country_code: req.country_code,
                    city: req.city,
                    bytes_transferred: req.bytes_transferred,
                    duration_ms: req.duration_ms,
                    success: req.success,
                    error_message: req.error_message,
                    accessed_at: req.accessed_at,
                    metadata: req.metadata,
                }
            }
        };
        
        let result = self.repository
            .upsert(entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(result.into()))
    }

    async fn list_trash(
        &self,
        request: Request<ListAccessLogTrashRequest>,
    ) -> Result<Response<ListAccessLogResponse>, Status> {
        let req = request.into_inner();
        
        let page = if req.page > 0 { req.page } else { 1 };
        let per_page = if req.per_page > 0 { req.per_page } else { 20 };
        
        let (items, total) = self.repository
            .list_deleted(page, per_page)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        let total_pages = ((total as f64) / (per_page as f64)).ceil() as i32;
        
        Ok(Response::new(ListAccessLogResponse {
            items: items.into_iter().map(Into::into).collect(),
            total: total as i64,
            page,
            per_page,
            total_pages,
        }))
    }

    async fn restore(
        &self,
        request: Request<RestoreAccessLogRequest>,
    ) -> Result<Response<ProtoAccessLog>, Status> {
        let req = request.into_inner();
        
        let restored = self.repository
            .restore(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(restored.into()))
    }

    async fn empty_trash(
        &self,
        _request: Request<EmptyAccessLogTrashRequest>,
    ) -> Result<Response<EmptyAccessLogTrashResponse>, Status> {
        let count = self.repository
            .empty_trash()
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(EmptyAccessLogTrashResponse {
            deleted_count: count as i64,
        }))
    }
    // ===========================================
    // Streaming RPCs
    // ===========================================

    /// Server streaming: Stream all AccessLogs matching criteria
    type StreamListStream = ReceiverStream<Result<ProtoAccessLog, Status>>;

    async fn stream_list(
        &self,
        request: Request<StreamAccessLogRequest>,
    ) -> Result<Response<Self::StreamListStream>, Status> {
        let req = request.into_inner();
        let (tx, rx) = mpsc::channel(128);
        let repository = self.repository.clone();
        
        tokio::spawn(async move {
            // Get items with streaming support
            let limit = if req.limit > 0 { req.limit as usize } else { usize::MAX };
            let sort_by = if req.sort_by.is_empty() { None } else { Some(req.sort_by.as_str()) };
            let sort_order = if req.sort_order.is_empty() { None } else { Some(req.sort_order.as_str()) };
            
            // Fetch items in batches
            let batch_size = 100;
            let mut page = 1;
            let mut sent = 0usize;
            
            loop {
                match repository.list(page, batch_size, sort_by, sort_order).await {
                    Ok((items, _total)) => {
                        if items.is_empty() {
                            break;
                        }
                        for item in items {
                            if sent >= limit {
                                return;
                            }
                            if tx.send(Ok(item.into())).await.is_err() {
                                return;
                            }
                            sent += 1;
                        }
                        page += 1;
                    }
                    Err(e) => {
                        let _ = tx.send(Err(Status::internal(e.to_string()))).await;
                        return;
                    }
                }
            }
        });
        
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    /// Client streaming: Bulk create AccessLogs from stream
    async fn stream_bulk_create(
        &self,
        request: Request<Streaming<CreateAccessLogRequest>>,
    ) -> Result<Response<BulkCreateAccessLogResponse>, Status> {
        let mut stream = request.into_inner();
        let mut entities = Vec::new();
        
        while let Some(req) = stream.next().await {
            let req = req?;
            let entity = AccessLog {
                id: Uuid::new_v4().to_string(),
                file_id: req.file_id,
                bucket_id: req.bucket_id,
                action: req.action,
                user_id: req.user_id,
                share_id: req.share_id,
                is_owner: req.is_owner,
                is_shared: req.is_shared,
                is_public: req.is_public,
                ip_address: req.ip_address,
                user_agent: req.user_agent,
                referer: req.referer,
                country_code: req.country_code,
                city: req.city,
                bytes_transferred: req.bytes_transferred,
                duration_ms: req.duration_ms,
                success: req.success,
                error_message: req.error_message,
                accessed_at: req.accessed_at,
                metadata: req.metadata,
            };
            entities.push(entity);
        }
        
        let count = entities.len() as i32;
        let created = self.repository
            .bulk_create(entities)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(BulkCreateAccessLogResponse {
            items: created.into_iter().map(Into::into).collect(),
            created_count: count,
        }))
    }

    /// Bidirectional streaming: Sync AccessLogs changes
    type SyncStreamStream = ReceiverStream<Result<SyncAccessLogResponse, Status>>;

    async fn sync_stream(
        &self,
        request: Request<Streaming<SyncAccessLogRequest>>,
    ) -> Result<Response<Self::SyncStreamStream>, Status> {
        let mut stream = request.into_inner();
        let (tx, rx) = mpsc::channel(128);
        let repository = self.repository.clone();
        
        tokio::spawn(async move {
            while let Some(result) = stream.next().await {
                let req = match result {
                    Ok(r) => r,
                    Err(e) => {
                        let _ = tx.send(Err(Status::internal(e.to_string()))).await;
                        continue;
                    }
                };
                
                let correlation_id = req.correlation_id.clone();
                
                // Process based on operation type
                let response = match req.operation {
                    Some(sync_access_log_request::Operation::Create(create_req)) => {
                        // Handle create
                        SyncAccessLogResponse {
                            result: None, // TODO: implement create logic
                            correlation_id,
                        }
                    }
                    Some(sync_access_log_request::Operation::Update(update_req)) => {
                        // Handle update
                        SyncAccessLogResponse {
                            result: None, // TODO: implement update logic
                            correlation_id,
                        }
                    }
                    Some(sync_access_log_request::Operation::Delete(delete_req)) => {
                        // Handle delete
                        SyncAccessLogResponse {
                            result: None, // TODO: implement delete logic
                            correlation_id,
                        }
                    }
                    None => {
                        SyncAccessLogResponse {
                            result: Some(sync_access_log_response::Result::Error(SyncError {
                                code: "NO_OPERATION".to_string(),
                                message: "No operation specified".to_string(),
                                details: Default::default(),
                            })),
                            correlation_id,
                        }
                    }
                };
                
                if tx.send(Ok(response)).await.is_err() {
                    break;
                }
            }
        });
        
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    /// Server streaming: Watch for AccessLog changes
    type WatchStream = ReceiverStream<Result<AccessLogEvent, Status>>;

    async fn watch(
        &self,
        request: Request<WatchAccessLogRequest>,
    ) -> Result<Response<Self::WatchStream>, Status> {
        let req = request.into_inner();
        let (tx, rx) = mpsc::channel(128);
        
        // TODO: Integrate with event bus/message broker
        // This is a placeholder that demonstrates the streaming pattern
        tokio::spawn(async move {
            // Keep connection alive - in real implementation
            // this would subscribe to an event bus
            let mut sequence = req.from_sequence.unwrap_or(0);
            
            loop {
                // In real implementation, wait for events from event bus
                tokio::time::sleep(tokio::time::Duration::from_secs(30)).await;
                
                // Send heartbeat or check if channel is still open
                if tx.is_closed() {
                    break;
                }
            }
        });
        
        Ok(Response::new(ReceiverStream::new(rx)))
    }

}

