//! FileShare gRPC service implementation
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use tonic::{Request, Response, Status};
use uuid::Uuid;

use crate::domain::entity::FileShare;
use crate::infrastructure::persistence::file_share_repository::FileShareRepository;

// Generated protobuf types
use crate::proto::file_share_v1::{
    file_share_service_server::file_shareService,
    FileShare as ProtoFileShare,
    ListFileShareRequest, ListFileShareResponse,
    CreateFileShareRequest,
    GetFileShareRequest,
    UpdateFileShareRequest,
    PatchFileShareRequest,
    DeleteFileShareRequest,
    BulkCreateFileShareRequest, BulkCreateFileShareResponse,
    UpsertFileShareRequest,
    ListFileShareTrashRequest,
    RestoreFileShareRequest,
    EmptyFileShareTrashRequest, EmptyFileShareTrashResponse,
    // Streaming types
    StreamFileShareRequest,
    SyncFileShareRequest, SyncFileShareResponse, SyncError,
    WatchFileShareRequest, FileShareEvent,
};

// Streaming imports
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tonic::Streaming;
use futures::StreamExt;

/// FileShare gRPC service implementation
pub struct FileShareGrpcService {
    repository: Arc<FileShareRepository>,
}

impl FileShareGrpcService {
    pub fn new(repository: Arc<FileShareRepository>) -> Self {
        Self { repository }
    }
}

impl From<FileShare> for ProtoFileShare {
    fn from(entity: FileShare) -> Self {
        Self {
            id: entity.id,
            file_id: entity.file_id,
            owner_id: entity.owner_id,
            token: entity.token,
            share_type: entity.share_type,
            permission: entity.permission,
            shared_with: entity.shared_with,
            password_hash: entity.password_hash,
            max_downloads: entity.max_downloads,
            download_count: entity.download_count,
            expires_at: entity.expires_at,
            is_active: entity.is_active,
            revoked_at: entity.revoked_at,
            revoked_by: entity.revoked_by,
            message: entity.message,
            metadata: entity.metadata,
        }
    }
}

#[tonic::async_trait]
impl file_shareService for FileShareGrpcService {
    async fn list(
        &self,
        request: Request<ListFileShareRequest>,
    ) -> Result<Response<ListFileShareResponse>, Status> {
        let req = request.into_inner();
        
        let page = if req.page > 0 { req.page } else { 1 };
        let per_page = if req.per_page > 0 { req.per_page } else { 20 };
        let sort_by = if req.sort_by.is_empty() { None } else { Some(req.sort_by.as_str()) };
        let sort_order = if req.sort_order.is_empty() { None } else { Some(req.sort_order.as_str()) };
        
        let (items, total) = self.repository
            .list(page, per_page, sort_by, sort_order)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        let total_pages = ((total as f64) / (per_page as f64)).ceil() as i32;
        
        Ok(Response::new(ListFileShareResponse {
            items: items.into_iter().map(Into::into).collect(),
            total: total as i64,
            page,
            per_page,
            total_pages,
        }))
    }

    async fn create(
        &self,
        request: Request<CreateFileShareRequest>,
    ) -> Result<Response<ProtoFileShare>, Status> {
        let req = request.into_inner();
        
        let entity = FileShare {
            id: Uuid::new_v4().to_string(),
            file_id: req.file_id,
            owner_id: req.owner_id,
            token: req.token,
            share_type: req.share_type,
            permission: req.permission,
            shared_with: req.shared_with,
            password_hash: req.password_hash,
            max_downloads: req.max_downloads,
            download_count: req.download_count,
            expires_at: req.expires_at,
            is_active: req.is_active,
            revoked_at: req.revoked_at,
            revoked_by: req.revoked_by,
            message: req.message,
            metadata: req.metadata,
        };
        
        let created = self.repository
            .create(entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(created.into()))
    }

    async fn get(
        &self,
        request: Request<GetFileShareRequest>,
    ) -> Result<Response<ProtoFileShare>, Status> {
        let req = request.into_inner();
        
        let entity = self.repository
            .find_by_id(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("FileShare not found: {}", req.id)))?;
        
        Ok(Response::new(entity.into()))
    }

    async fn update(
        &self,
        request: Request<UpdateFileShareRequest>,
    ) -> Result<Response<ProtoFileShare>, Status> {
        let req = request.into_inner();
        
        let existing = self.repository
            .find_by_id(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("FileShare not found: {}", req.id)))?;
        
        let entity = FileShare {
            id: existing.id,
            file_id: req.file_id,
            owner_id: req.owner_id,
            token: req.token,
            share_type: req.share_type,
            permission: req.permission,
            shared_with: req.shared_with,
            password_hash: req.password_hash,
            max_downloads: req.max_downloads,
            download_count: req.download_count,
            expires_at: req.expires_at,
            is_active: req.is_active,
            revoked_at: req.revoked_at,
            revoked_by: req.revoked_by,
            message: req.message,
            metadata: req.metadata,
        };
        
        let updated = self.repository
            .update(&req.id, entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(updated.into()))
    }

    async fn patch(
        &self,
        request: Request<PatchFileShareRequest>,
    ) -> Result<Response<ProtoFileShare>, Status> {
        let req = request.into_inner();
        
        let mut existing = self.repository
            .find_by_id(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("FileShare not found: {}", req.id)))?;
        
        if let Some(value) = req.file_id {
            existing.file_id = value;
        }
        if let Some(value) = req.owner_id {
            existing.owner_id = value;
        }
        if let Some(value) = req.token {
            existing.token = value;
        }
        if let Some(value) = req.share_type {
            existing.share_type = value;
        }
        if let Some(value) = req.permission {
            existing.permission = value;
        }
        if let Some(value) = req.shared_with {
            existing.shared_with = value;
        }
        if let Some(value) = req.password_hash {
            existing.password_hash = value;
        }
        if let Some(value) = req.max_downloads {
            existing.max_downloads = value;
        }
        if let Some(value) = req.download_count {
            existing.download_count = value;
        }
        if let Some(value) = req.expires_at {
            existing.expires_at = value;
        }
        if let Some(value) = req.is_active {
            existing.is_active = value;
        }
        if let Some(value) = req.revoked_at {
            existing.revoked_at = value;
        }
        if let Some(value) = req.revoked_by {
            existing.revoked_by = value;
        }
        if let Some(value) = req.message {
            existing.message = value;
        }
        if let Some(value) = req.metadata {
            existing.metadata = value;
        }
        existing.updated_at = chrono::Utc::now();
        
        let updated = self.repository
            .update(&req.id, existing)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(updated.into()))
    }

    async fn delete(
        &self,
        request: Request<DeleteFileShareRequest>,
    ) -> Result<Response<()>, Status> {
        let req = request.into_inner();
        
        self.repository
            .soft_delete(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(()))
    }

    async fn bulk_create(
        &self,
        request: Request<BulkCreateFileShareRequest>,
    ) -> Result<Response<BulkCreateFileShareResponse>, Status> {
        let req = request.into_inner();
        
        let entities: Vec<FileShare> = req.items
            .into_iter()
            .map(|item| FileShare {
                id: Uuid::new_v4().to_string(),
                file_id: item.file_id,
                owner_id: item.owner_id,
                token: item.token,
                share_type: item.share_type,
                permission: item.permission,
                shared_with: item.shared_with,
                password_hash: item.password_hash,
                max_downloads: item.max_downloads,
                download_count: item.download_count,
                expires_at: item.expires_at,
                is_active: item.is_active,
                revoked_at: item.revoked_at,
                revoked_by: item.revoked_by,
                message: item.message,
                metadata: item.metadata,
            })
            .collect();
        
        let count = entities.len() as i32;
        let created = self.repository
            .bulk_create(entities)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(BulkCreateFileShareResponse {
            items: created.into_iter().map(Into::into).collect(),
            created_count: count,
        }))
    }

    async fn upsert(
        &self,
        request: Request<UpsertFileShareRequest>,
    ) -> Result<Response<ProtoFileShare>, Status> {
        let req = request.into_inner();
        
        let key_field = if req.key_field.is_empty() { "id" } else { &req.key_field };
        let existing = self.repository
            .find_by_field(key_field, &req.key_value)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        let entity = match existing {
            Some(mut e) => {
                e.file_id = req.file_id;
                e.owner_id = req.owner_id;
                e.token = req.token;
                e.share_type = req.share_type;
                e.permission = req.permission;
                e.shared_with = req.shared_with;
                e.password_hash = req.password_hash;
                e.max_downloads = req.max_downloads;
                e.download_count = req.download_count;
                e.expires_at = req.expires_at;
                e.is_active = req.is_active;
                e.revoked_at = req.revoked_at;
                e.revoked_by = req.revoked_by;
                e.message = req.message;
                e.metadata = req.metadata;
                e
            }
            None => {
                FileShare {
                    id: Uuid::new_v4().to_string(),
                    file_id: req.file_id,
                    owner_id: req.owner_id,
                    token: req.token,
                    share_type: req.share_type,
                    permission: req.permission,
                    shared_with: req.shared_with,
                    password_hash: req.password_hash,
                    max_downloads: req.max_downloads,
                    download_count: req.download_count,
                    expires_at: req.expires_at,
                    is_active: req.is_active,
                    revoked_at: req.revoked_at,
                    revoked_by: req.revoked_by,
                    message: req.message,
                    metadata: req.metadata,
                }
            }
        };
        
        let result = self.repository
            .upsert(entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(result.into()))
    }

    async fn list_trash(
        &self,
        request: Request<ListFileShareTrashRequest>,
    ) -> Result<Response<ListFileShareResponse>, Status> {
        let req = request.into_inner();
        
        let page = if req.page > 0 { req.page } else { 1 };
        let per_page = if req.per_page > 0 { req.per_page } else { 20 };
        
        let (items, total) = self.repository
            .list_deleted(page, per_page)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        let total_pages = ((total as f64) / (per_page as f64)).ceil() as i32;
        
        Ok(Response::new(ListFileShareResponse {
            items: items.into_iter().map(Into::into).collect(),
            total: total as i64,
            page,
            per_page,
            total_pages,
        }))
    }

    async fn restore(
        &self,
        request: Request<RestoreFileShareRequest>,
    ) -> Result<Response<ProtoFileShare>, Status> {
        let req = request.into_inner();
        
        let restored = self.repository
            .restore(&req.id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(restored.into()))
    }

    async fn empty_trash(
        &self,
        _request: Request<EmptyFileShareTrashRequest>,
    ) -> Result<Response<EmptyFileShareTrashResponse>, Status> {
        let count = self.repository
            .empty_trash()
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(EmptyFileShareTrashResponse {
            deleted_count: count as i64,
        }))
    }
    // ===========================================
    // Streaming RPCs
    // ===========================================

    /// Server streaming: Stream all FileShares matching criteria
    type StreamListStream = ReceiverStream<Result<ProtoFileShare, Status>>;

    async fn stream_list(
        &self,
        request: Request<StreamFileShareRequest>,
    ) -> Result<Response<Self::StreamListStream>, Status> {
        let req = request.into_inner();
        let (tx, rx) = mpsc::channel(128);
        let repository = self.repository.clone();
        
        tokio::spawn(async move {
            // Get items with streaming support
            let limit = if req.limit > 0 { req.limit as usize } else { usize::MAX };
            let sort_by = if req.sort_by.is_empty() { None } else { Some(req.sort_by.as_str()) };
            let sort_order = if req.sort_order.is_empty() { None } else { Some(req.sort_order.as_str()) };
            
            // Fetch items in batches
            let batch_size = 100;
            let mut page = 1;
            let mut sent = 0usize;
            
            loop {
                match repository.list(page, batch_size, sort_by, sort_order).await {
                    Ok((items, _total)) => {
                        if items.is_empty() {
                            break;
                        }
                        for item in items {
                            if sent >= limit {
                                return;
                            }
                            if tx.send(Ok(item.into())).await.is_err() {
                                return;
                            }
                            sent += 1;
                        }
                        page += 1;
                    }
                    Err(e) => {
                        let _ = tx.send(Err(Status::internal(e.to_string()))).await;
                        return;
                    }
                }
            }
        });
        
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    /// Client streaming: Bulk create FileShares from stream
    async fn stream_bulk_create(
        &self,
        request: Request<Streaming<CreateFileShareRequest>>,
    ) -> Result<Response<BulkCreateFileShareResponse>, Status> {
        let mut stream = request.into_inner();
        let mut entities = Vec::new();
        
        while let Some(req) = stream.next().await {
            let req = req?;
            let entity = FileShare {
                id: Uuid::new_v4().to_string(),
                file_id: req.file_id,
                owner_id: req.owner_id,
                token: req.token,
                share_type: req.share_type,
                permission: req.permission,
                shared_with: req.shared_with,
                password_hash: req.password_hash,
                max_downloads: req.max_downloads,
                download_count: req.download_count,
                expires_at: req.expires_at,
                is_active: req.is_active,
                revoked_at: req.revoked_at,
                revoked_by: req.revoked_by,
                message: req.message,
                metadata: req.metadata,
            };
            entities.push(entity);
        }
        
        let count = entities.len() as i32;
        let created = self.repository
            .bulk_create(entities)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(Response::new(BulkCreateFileShareResponse {
            items: created.into_iter().map(Into::into).collect(),
            created_count: count,
        }))
    }

    /// Bidirectional streaming: Sync FileShares changes
    type SyncStreamStream = ReceiverStream<Result<SyncFileShareResponse, Status>>;

    async fn sync_stream(
        &self,
        request: Request<Streaming<SyncFileShareRequest>>,
    ) -> Result<Response<Self::SyncStreamStream>, Status> {
        let mut stream = request.into_inner();
        let (tx, rx) = mpsc::channel(128);
        let repository = self.repository.clone();
        
        tokio::spawn(async move {
            while let Some(result) = stream.next().await {
                let req = match result {
                    Ok(r) => r,
                    Err(e) => {
                        let _ = tx.send(Err(Status::internal(e.to_string()))).await;
                        continue;
                    }
                };
                
                let correlation_id = req.correlation_id.clone();
                
                // Process based on operation type
                let response = match req.operation {
                    Some(sync_file_share_request::Operation::Create(create_req)) => {
                        // Handle create
                        SyncFileShareResponse {
                            result: None, // TODO: implement create logic
                            correlation_id,
                        }
                    }
                    Some(sync_file_share_request::Operation::Update(update_req)) => {
                        // Handle update
                        SyncFileShareResponse {
                            result: None, // TODO: implement update logic
                            correlation_id,
                        }
                    }
                    Some(sync_file_share_request::Operation::Delete(delete_req)) => {
                        // Handle delete
                        SyncFileShareResponse {
                            result: None, // TODO: implement delete logic
                            correlation_id,
                        }
                    }
                    None => {
                        SyncFileShareResponse {
                            result: Some(sync_file_share_response::Result::Error(SyncError {
                                code: "NO_OPERATION".to_string(),
                                message: "No operation specified".to_string(),
                                details: Default::default(),
                            })),
                            correlation_id,
                        }
                    }
                };
                
                if tx.send(Ok(response)).await.is_err() {
                    break;
                }
            }
        });
        
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    /// Server streaming: Watch for FileShare changes
    type WatchStream = ReceiverStream<Result<FileShareEvent, Status>>;

    async fn watch(
        &self,
        request: Request<WatchFileShareRequest>,
    ) -> Result<Response<Self::WatchStream>, Status> {
        let req = request.into_inner();
        let (tx, rx) = mpsc::channel(128);
        
        // TODO: Integrate with event bus/message broker
        // This is a placeholder that demonstrates the streaming pattern
        tokio::spawn(async move {
            // Keep connection alive - in real implementation
            // this would subscribe to an event bus
            let mut sequence = req.from_sequence.unwrap_or(0);
            
            loop {
                // In real implementation, wait for events from event bus
                tokio::time::sleep(tokio::time::Duration::from_secs(30)).await;
                
                // Send heartbeat or check if channel is still open
                if tx.is_closed() {
                    break;
                }
            }
        });
        
        Ok(Response::new(ReceiverStream::new(rx)))
    }

}

// State transition RPC implementations

// Additional proto messages for state transitions would be:
// message ExpireFileShareRequest { string id = 1; }
// message ExhaustFileShareRequest { string id = 1; }
// message RevokeFileShareRequest { string id = 1; }

impl FileShareGrpcService {
    /// Execute expire state transition
    pub async fn expire(
        &self,
        id: &str,
        user_role: Option<&str>,
    ) -> Result<FileShare, Status> {
        let mut entity = self.repository
            .find_by_id(id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("FileShare not found: {}", id)))?;
        
        // TODO: Validate transition using state machine
        // let sm = FileShareStateMachine::new(entity.is_active.clone());
        // if !sm.can_transition_with_role(FileShareTransition::Expire, user_role) {
        //     return Err(Status::permission_denied("Transition not allowed"));
        // }
        
        // Apply transition
        entity.is_active = "expired" .to_string(); // TODO: Use proper enum
        entity.updated_at = chrono::Utc::now();
        
        let updated = self.repository
            .update(id, entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(updated)
    }

    /// Execute exhaust state transition
    pub async fn exhaust(
        &self,
        id: &str,
        user_role: Option<&str>,
    ) -> Result<FileShare, Status> {
        let mut entity = self.repository
            .find_by_id(id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("FileShare not found: {}", id)))?;
        
        // TODO: Validate transition using state machine
        // let sm = FileShareStateMachine::new(entity.is_active.clone());
        // if !sm.can_transition_with_role(FileShareTransition::Exhaust, user_role) {
        //     return Err(Status::permission_denied("Transition not allowed"));
        // }
        
        // Apply transition
        entity.is_active = "exhausted" .to_string(); // TODO: Use proper enum
        entity.updated_at = chrono::Utc::now();
        
        let updated = self.repository
            .update(id, entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(updated)
    }

    /// Execute revoke state transition
    pub async fn revoke(
        &self,
        id: &str,
        user_role: Option<&str>,
    ) -> Result<FileShare, Status> {
        let mut entity = self.repository
            .find_by_id(id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?
            .ok_or_else(|| Status::not_found(format!("FileShare not found: {}", id)))?;
        
        // TODO: Validate transition using state machine
        // let sm = FileShareStateMachine::new(entity.is_active.clone());
        // if !sm.can_transition_with_role(FileShareTransition::Revoke, user_role) {
        //     return Err(Status::permission_denied("Transition not allowed"));
        // }
        
        // Apply transition
        entity.is_active = "revoked" .to_string(); // TODO: Use proper enum
        entity.updated_at = chrono::Utc::now();
        
        let updated = self.repository
            .update(id, entity)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        
        Ok(updated)
    }

}
