//! Specifications for StoredFile aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Entity-specific predicate structs implementing `backbone_core::Specification`.
//! Combinators (AND/OR/NOT) are available via the trait methods — no duplication.

use backbone_core::Specification;
use crate::domain::entity::StoredFile;

pub use backbone_core::{AndSpecification, OrSpecification, NotSpecification};

// ─── Entity-specific predicates ──────────────────────────────────────────────
//
// Add entity-specific predicate structs below.
// Each predicate implements `Specification<StoredFile>` and can be combined
// using `.and()`, `.or()`, `.not()` from the trait.
//
// Example:
//   let spec = ActiveSpec.and(VerifiedSpec);
//   if spec.is_satisfied_by(&entity) { ... }

// <<< CUSTOM
// Add predicate structs here. Example:
//
// pub struct ActiveStoredFileSpec;
// impl Specification<StoredFile> for ActiveStoredFileSpec {
//     fn is_satisfied_by(&self, e: &StoredFile) -> bool {
//         // e.is_active
//         todo!()
//     }
// }
// <<< CUSTOM SPECIFICATIONS START >>>
// Add your custom specifications here
// pub struct StoredFileHasValidEmailSpec;
// impl StoredFileSpecification for StoredFileHasValidEmailSpec {
//     fn is_satisfied_by(&self, entity: &StoredFile) -> bool {
//         entity.email.contains('@')
// END CUSTOM
// END CUSTOM