//! Specifications for UserQuota aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Entity-specific predicate structs implementing `backbone_core::Specification`.
//! Combinators (AND/OR/NOT) are available via the trait methods — no duplication.

use backbone_core::Specification;
use crate::domain::entity::UserQuota;

pub use backbone_core::{AndSpecification, OrSpecification, NotSpecification};

// ─── Entity-specific predicates ──────────────────────────────────────────────
//
// Add entity-specific predicate structs below.
// Each predicate implements `Specification<UserQuota>` and can be combined
// using `.and()`, `.or()`, `.not()` from the trait.
//
// Example:
//   let spec = ActiveSpec.and(VerifiedSpec);
//   if spec.is_satisfied_by(&entity) { ... }

// <<< CUSTOM
// Add predicate structs here. Example:
//
// pub struct ActiveUserQuotaSpec;
// impl Specification<UserQuota> for ActiveUserQuotaSpec {
//     fn is_satisfied_by(&self, e: &UserQuota) -> bool {
//         // e.is_active
//         todo!()
//     }
// }
// <<< CUSTOM SPECIFICATIONS START >>>
// Add your custom specifications here
// pub struct UserQuotaHasValidEmailSpec;
// impl UserQuotaSpecification for UserQuotaHasValidEmailSpec {
//     fn is_satisfied_by(&self, entity: &UserQuota) -> bool {
//         entity.email.contains('@')
// END CUSTOM
// END CUSTOM