//! Domain policies
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod access_log_domain_policy;
pub mod bucket_domain_policy;
pub mod content_hash_domain_policy;
pub mod conversion_job_domain_policy;
pub mod file_comment_domain_policy;
pub mod file_lock_domain_policy;
pub mod file_share_domain_policy;
pub mod file_version_domain_policy;
pub mod processing_job_domain_policy;
pub mod stored_file_domain_policy;
pub mod thumbnail_domain_policy;
pub mod upload_session_domain_policy;
pub mod user_quota_domain_policy;

pub use access_log_domain_policy::AccessLogDomainPolicy;
pub use bucket_domain_policy::BucketDomainPolicy;
pub use content_hash_domain_policy::ContentHashDomainPolicy;
pub use conversion_job_domain_policy::ConversionJobDomainPolicy;
pub use file_comment_domain_policy::FileCommentDomainPolicy;
pub use file_lock_domain_policy::FileLockDomainPolicy;
pub use file_share_domain_policy::FileShareDomainPolicy;
pub use file_version_domain_policy::FileVersionDomainPolicy;
pub use processing_job_domain_policy::ProcessingJobDomainPolicy;
pub use stored_file_domain_policy::StoredFileDomainPolicy;
pub use thumbnail_domain_policy::ThumbnailDomainPolicy;
pub use upload_session_domain_policy::UploadSessionDomainPolicy;
pub use user_quota_domain_policy::UserQuotaDomainPolicy;

// <<< CUSTOM
// END CUSTOM
