//! Domain service for ProcessingJob aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This service contains domain business logic for ProcessingJob operations.
//! Add your custom business rules and domain operations here.

// ============================================================================
// IMPORTS - Add custom imports below
// ============================================================================

use anyhow::Result;

use crate::ProcessingJob;
// <<< CUSTOM IMPORTS START >>>

// <<< CUSTOM IMPORTS START >>>
// Add your custom imports here
// <<< CUSTOM IMPORTS END >>>

// ============================================================================
// DOMAIN SERVICE
// ============================================================================

/// Domain service for ProcessingJob business operations
///
/// This service contains:
/// - Business validation rules
/// - Domain operations that span multiple entities
/// - Complex business logic
///
/// Note: This is a stateless service. State should be in entities.
pub struct ProcessingJobDomainService;

impl ProcessingJobDomainService {
    /// Create a new domain service instance
    pub fn new() -> Self {
        Self
    }

    // =========================================================================
    // Generated Business Operations
    // =========================================================================

    /// Validate a processing_job entity for business rules
    ///
    /// Override this method to add custom validation logic.
    pub fn validate(&self, _entity: &ProcessingJob) -> Result<()> {
        // Default validation - check required fields
        Ok(())
    }

    /// Check if a processing_job can be created
    ///
    /// Add custom business rules that must be satisfied before creation.
    pub fn can_create(&self, entity: &ProcessingJob) -> Result<bool> {
        self.validate(entity)?;
        Ok(true)
    }

    /// Check if a processing_job can be updated
    pub fn can_update(&self, _current: &ProcessingJob, _updated: &ProcessingJob) -> Result<bool> {
        // Add update permission/business logic here
        Ok(true)
    }

    /// Check if a processing_job can be deleted
    pub fn can_delete(&self, _entity: &ProcessingJob) -> Result<bool> {
        // Add deletion permission/business logic here
        Ok(true)
    }

    // =========================================================================
    // Custom Business Operations
    // =========================================================================
    // <<< CUSTOM OPERATIONS START >>>

    // <<< CUSTOM OPERATIONS START >>>
    // Add your custom domain operations here
    // Example:
    // pub fn calculate_something(&self, entity: &ProcessingJob) -> Result<i32> {
    //     // Business logic here
    //     Ok(0)
    // }
    // <<< CUSTOM OPERATIONS END >>>
}

impl Default for ProcessingJobDomainService {
    fn default() -> Self {
        Self::new()
    }
}