//! Application service for AccessLog entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `access_log_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAccessLogDto, UpdateAccessLogDto};
use crate::domain::entity::AccessLog;
use crate::infrastructure::persistence::AccessLogRepository;

/// Application service for AccessLog entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `access_log_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AccessLogServiceCustom {
///     inner: Arc<AccessLogService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AccessLogService = GenericCrudService<
    AccessLog,
    CreateAccessLogDto,
    UpdateAccessLogDto,
    AccessLogRepository,
>;

// <<< CUSTOM
// END CUSTOM
