//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

// <<< CUSTOM - Custom business logic services
mod locking_service;
mod deduplication_service;
mod multipart_upload_service;
mod conversion_service;
mod cdn_service;
mod video_thumbnail_service;
mod document_preview_service;
mod file_service;

pub use locking_service::LockingService;
pub use deduplication_service::DeduplicationService;
pub use multipart_upload_service::MultipartUploadService;
pub use conversion_service::ConversionService;
#[allow(deprecated)]
pub use cdn_service::CdnService;
pub use video_thumbnail_service::VideoThumbnailService;
pub use document_preview_service::DocumentPreviewService;
pub use file_service::{FileMeta, FileService};
// END CUSTOM
pub mod access_log_service;
pub mod bucket_service;
pub mod content_hash_service;
pub mod conversion_job_service;
pub mod file_comment_service;
pub mod file_lock_service;
pub mod file_share_service;
pub mod file_version_service;
pub mod processing_job_service;
pub mod stored_file_service;
pub mod thumbnail_service;
pub mod upload_session_service;
pub mod user_quota_service;

// <<< CUSTOM
// END CUSTOM

pub use access_log_service::AccessLogService;
pub use bucket_service::BucketService;
pub use content_hash_service::ContentHashService;
pub use conversion_job_service::ConversionJobService;
pub use file_comment_service::FileCommentService;
pub use file_lock_service::FileLockService;
pub use file_share_service::FileShareService;
pub use file_version_service::FileVersionService;
pub use processing_job_service::ProcessingJobService;
pub use stored_file_service::StoredFileService;
pub use thumbnail_service::ThumbnailService;
pub use upload_session_service::UploadSessionService;
pub use user_quota_service::UserQuotaService;
// <<< CUSTOM
// END CUSTOM