//! Application service for ProcessingJob entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `processing_job_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateProcessingJobDto, UpdateProcessingJobDto};
use crate::domain::entity::ProcessingJob;
use crate::infrastructure::persistence::ProcessingJobRepository;

/// Application service for ProcessingJob entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `processing_job_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ProcessingJobServiceCustom {
///     inner: Arc<ProcessingJobService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ProcessingJobService = GenericCrudService<
    ProcessingJob,
    CreateProcessingJobDto,
    UpdateProcessingJobDto,
    ProcessingJobRepository,
>;

// <<< CUSTOM
// END CUSTOM
