//! Application service for Thumbnail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `thumbnail_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateThumbnailDto, UpdateThumbnailDto};
use crate::domain::entity::Thumbnail;
use crate::infrastructure::persistence::ThumbnailRepository;

/// Application service for Thumbnail entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `thumbnail_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ThumbnailServiceCustom {
///     inner: Arc<ThumbnailService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ThumbnailService = GenericCrudService<
    Thumbnail,
    CreateThumbnailDto,
    UpdateThumbnailDto,
    ThumbnailRepository,
>;

// <<< CUSTOM
// END CUSTOM
