//! Auth configuration for Bucket handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides:
//! - Permission definitions for CRUD operations
//! - Role-based guards
//! - Auth middleware configuration

use std::sync::Arc;

use crate::application::middleware::auth::AuthContext;
use axum::{
    extract::{Request, State},
    http::StatusCode,
    middleware::Next,
    response::Response,
};

// ==========================================================================
// Permission Constants
// ==========================================================================

/// Permission identifiers for Bucket operations
pub mod buckets {
    /// Permission to list bucket entities
    pub const LIST: &str = "bucket:list";
    /// Permission to read bucket entity details
    pub const READ: &str = "bucket:read";
    /// Permission to create bucket entities
    pub const CREATE: &str = "bucket:create";
    /// Permission to update bucket entities
    pub const UPDATE: &str = "bucket:update";
    /// Permission to delete bucket entities
    pub const DELETE: &str = "bucket:delete";
    /// Permission to restore deleted bucket entities
    pub const RESTORE: &str = "bucket:restore";
    /// Permission to view bucket trash
    pub const TRASH: &str = "bucket:trash";
    /// Permission to empty bucket trash (permanent delete)
    pub const EMPTY_TRASH: &str = "bucket:empty_trash";
    /// Permission to bulk create bucket entities
    pub const BULK_CREATE: &str = "bucket:bulk_create";
    /// Permission to upsert bucket entities
    pub const UPSERT: &str = "bucket:upsert";

    // State transition permissions
    /// Permission to execute lock transition
    pub const TRANSITION_LOCK: &str = "bucket:transition:lock";
    /// Permission to execute unlock transition
    pub const TRANSITION_UNLOCK: &str = "bucket:transition:unlock";
    /// Permission to execute archive transition
    pub const TRANSITION_ARCHIVE: &str = "bucket:transition:archive";
    /// Permission to execute restore transition
    pub const TRANSITION_RESTORE: &str = "bucket:transition:restore";
    /// Permission to execute delete transition
    pub const TRANSITION_DELETE: &str = "bucket:transition:delete";

    /// Get all permissions for this entity
    pub fn all() -> Vec<&'static str> {
        vec![
            LIST,
            READ,
            CREATE,
            UPDATE,
            DELETE,
            RESTORE,
            TRASH,
            EMPTY_TRASH,
            BULK_CREATE,
            UPSERT,
            TRANSITION_LOCK,
            TRANSITION_UNLOCK,
            TRANSITION_ARCHIVE,
            TRANSITION_RESTORE,
            TRANSITION_DELETE,
        ]
    }
}

// ==========================================================================
// Permission Checking
// ==========================================================================

/// Check if auth context has a specific permission
pub fn has_permission(auth: &AuthContext, permission: &str) -> bool {
    auth.has_permission(permission)
}

/// Check if auth context has a specific role
pub fn has_role(auth: &AuthContext, role: &str) -> bool {
    auth.has_role(role)
}

/// Check if auth context has all of the required roles
pub fn has_all_roles(auth: &AuthContext, roles: &[&str]) -> bool {
    auth.has_all_roles(roles)
}

/// Check if auth context has any of the required permissions
pub fn has_any_permission(auth: &AuthContext, permissions: &[&str]) -> bool {
    permissions.iter().any(|p| auth.has_permission(p))
}

// ==========================================================================
// Permission Guards (Axum Middleware)
// ==========================================================================

/// Note: Axum middleware should be implemented as async fn, not impl Fn
/// This avoids E0562: `impl Trait` is not allowed in the return type of `Fn` trait bounds

// ==========================================================================
// Bucket Specific Guards
// ==========================================================================

/// Guard that requires list permission for bucket
pub async fn require_list_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::LIST) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires read permission for bucket
pub async fn require_read_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::READ) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires create permission for bucket
pub async fn require_create_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::CREATE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires update permission for bucket
pub async fn require_update_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::UPDATE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires delete permission for bucket
pub async fn require_delete_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::DELETE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires restore permission for bucket
pub async fn require_restore_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::RESTORE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires view trash permission for bucket
pub async fn require_trash_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::TRASH) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires empty trash permission for bucket
pub async fn require_empty_trash_bucket(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, buckets::EMPTY_TRASH) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

