-- AccessLog Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the access_logs table.
-- Customize this file to add your initial data.

-- INSERT INTO access_logs (
--     id,
--     file_id,
--     bucket_id,
--     action,
--     user_id,
--     share_id,
--     is_owner,
--     is_shared,
--     is_public,
--     ip_address,
--     user_agent,
--     referer,
--     country_code,
--     city,
--     bytes_transferred,
--     duration_ms,
--     success,
--     error_message,
--     accessed_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO access_logs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

