-- ContentHash Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the content_hashes table.
-- Customize this file to add your initial data.

-- INSERT INTO content_hashes (
--     id,
--     hash,
--     size_bytes,
--     storage_key,
--     storage_backend,
--     reference_count,
--     first_uploaded_at,
--     last_referenced_at,
--     fingerprint,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO content_hashes (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

