-- FileComment Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the file_comments table.
-- Customize this file to add your initial data.

-- INSERT INTO file_comments (
--     id,
--     file_id,
--     user_id,
--     parent_id,
--     content,
--     annotation_region,
--     mentions,
--     resolved,
--     resolved_by,
--     resolved_at,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO file_comments (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

