-- UserQuota Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the user_quotas table.
-- Customize this file to add your initial data.

-- INSERT INTO user_quotas (
--     id,
--     user_id,
--     limit_bytes,
--     used_bytes,
--     file_count,
--     max_file_size,
--     max_file_count,
--     tier,
--     quota_status,
--     warning_threshold_percent,
--     last_warning_sent_at,
--     peak_usage_bytes,
--     peak_usage_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO user_quotas (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

