-- Migration: Create file_comments table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS file_comments (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    file_id UUID NOT NULL,
    user_id UUID NOT NULL,
    parent_id UUID,
    content TEXT NOT NULL,
    annotation_region JSONB,
    mentions UUID[] NOT NULL,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_by UUID,
    resolved_at TIMESTAMPTZ,
    status comment_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_file_comments_file_id ON file_comments (file_id);

CREATE INDEX IF NOT EXISTS idx_file_comments_parent_id ON file_comments (parent_id);

CREATE INDEX IF NOT EXISTS idx_file_comments_user_id ON file_comments (user_id);

CREATE INDEX IF NOT EXISTS idx_file_comments_resolved ON file_comments (resolved);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_file_comments_metadata_gin ON file_comments USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_file_comments_metadata_deleted_at ON file_comments ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION file_comments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS file_comments_insert_audit ON file_comments;
CREATE TRIGGER file_comments_insert_audit BEFORE INSERT ON file_comments
    FOR EACH ROW EXECUTE FUNCTION file_comments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS file_comments_update_audit ON file_comments;
CREATE TRIGGER file_comments_update_audit BEFORE UPDATE ON file_comments
    FOR EACH ROW EXECUTE FUNCTION file_comments_audit_timestamp();

