-- Migration: Create upload_sessions table
-- Generated by metaphor-schema

CREATE TABLE IF NOT EXISTS upload_sessions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    bucket_id UUID NOT NULL,
    user_id UUID NOT NULL,
    path TEXT NOT NULL,
    filename TEXT NOT NULL,
    mime_type TEXT,
    file_size BIGINT NOT NULL,
    chunk_size INTEGER NOT NULL,
    total_chunks INTEGER NOT NULL,
    uploaded_chunks INTEGER NOT NULL DEFAULT 0,
    status upload_status NOT NULL DEFAULT 'initiated',
    storage_backend storage_backend NOT NULL DEFAULT 'local',
    completed_parts INTEGER[] NOT NULL,
    part_etags JSONB,
    expires_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_upload_sessions_user_id_status ON upload_sessions (user_id, status);

CREATE INDEX IF NOT EXISTS idx_upload_sessions_expires_at ON upload_sessions (expires_at);

CREATE INDEX IF NOT EXISTS idx_upload_sessions_bucket_id_status ON upload_sessions (bucket_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_upload_sessions_metadata_gin ON upload_sessions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_upload_sessions_metadata_deleted_at ON upload_sessions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_upload_sessions_metadata_created_at ON upload_sessions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_upload_sessions_metadata_updated_at ON upload_sessions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION upload_sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS upload_sessions_insert_audit ON upload_sessions;
CREATE TRIGGER upload_sessions_insert_audit BEFORE INSERT ON upload_sessions
    FOR EACH ROW EXECUTE FUNCTION upload_sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS upload_sessions_update_audit ON upload_sessions;
CREATE TRIGGER upload_sessions_update_audit BEFORE UPDATE ON upload_sessions
    FOR EACH ROW EXECUTE FUNCTION upload_sessions_audit_timestamp();
