-- Migration: Create stored_files table
-- Generated by metaphor-schema

CREATE TABLE IF NOT EXISTS stored_files (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    bucket_id UUID NOT NULL,
    owner_id UUID NOT NULL,
    path TEXT NOT NULL,
    original_name TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    mime_type TEXT NOT NULL,
    checksum TEXT,
    is_compressed BOOLEAN NOT NULL DEFAULT FALSE,
    original_size BIGINT,
    compression_algorithm TEXT,
    is_scanned BOOLEAN NOT NULL DEFAULT FALSE,
    scan_result JSONB,
    threat_level threat_level,
    has_thumbnail BOOLEAN NOT NULL DEFAULT FALSE,
    thumbnail_path TEXT,
    has_video_thumbnail BOOLEAN NOT NULL DEFAULT FALSE,
    has_document_preview BOOLEAN NOT NULL DEFAULT FALSE,
    processing_status processing_status,
    content_hash_id UUID,
    cdn_url TEXT,
    cdn_url_expires_at TIMESTAMPTZ,
    owner_module TEXT,
    owner_entity TEXT,
    owner_entity_id UUID,
    field_name TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status file_status NOT NULL DEFAULT 'active',
    storage_key TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    previous_version_id UUID,
    download_count INTEGER NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_stored_files_bucket_id_path_(metadata->>'deleted_at') ON stored_files (bucket_id, path, ((metadata->>'deleted_at')));

CREATE INDEX IF NOT EXISTS idx_stored_files_owner_id ON stored_files (owner_id);

CREATE INDEX IF NOT EXISTS idx_stored_files_bucket_id ON stored_files (bucket_id);

CREATE INDEX IF NOT EXISTS idx_stored_files_status ON stored_files (status);

CREATE INDEX IF NOT EXISTS idx_stored_files_mime_type ON stored_files (mime_type);

CREATE INDEX IF NOT EXISTS idx_stored_files_owner_id_status ON stored_files (owner_id, status);

CREATE INDEX IF NOT EXISTS idx_stored_files_(metadata->>'created_at') ON stored_files (((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_stored_files_checksum ON stored_files (checksum);

CREATE INDEX IF NOT EXISTS idx_stored_files_content_hash_id ON stored_files (content_hash_id);

CREATE INDEX IF NOT EXISTS idx_stored_files_cdn_url_expires_at ON stored_files (cdn_url_expires_at);

CREATE INDEX IF NOT EXISTS idx_stored_files_processing_status ON stored_files (processing_status);

CREATE INDEX IF NOT EXISTS idx_stored_files_owner_module_owner_entity_owner_entity_id ON stored_files (owner_module, owner_entity, owner_entity_id);

CREATE INDEX IF NOT EXISTS idx_stored_files_owner_entity_id ON stored_files (owner_entity_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_stored_files_metadata_gin ON stored_files USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_stored_files_metadata_deleted_at ON stored_files ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_stored_files_metadata_created_at ON stored_files ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_stored_files_metadata_updated_at ON stored_files ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION stored_files_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS stored_files_insert_audit ON stored_files;
CREATE TRIGGER stored_files_insert_audit BEFORE INSERT ON stored_files
    FOR EACH ROW EXECUTE FUNCTION stored_files_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS stored_files_update_audit ON stored_files;
CREATE TRIGGER stored_files_update_audit BEFORE UPDATE ON stored_files
    FOR EACH ROW EXECUTE FUNCTION stored_files_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE stored_files ADD CONSTRAINT fk_stored_files_bucket_id FOREIGN KEY (bucket_id) REFERENCES buckets (id);
ALTER TABLE stored_files ADD CONSTRAINT fk_stored_files_previous_version_id FOREIGN KEY (previous_version_id) REFERENCES stored_files (id);
ALTER TABLE stored_files ADD CONSTRAINT fk_stored_files_content_hash_id FOREIGN KEY (content_hash_id) REFERENCES content_hashes (id);
