-- Enum types for bucket module
-- Generated by metaphor-schema

-- Create bucket_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bucket_type') THEN
        CREATE TYPE bucket_type AS ENUM ('user', 'shared', 'system', 'temp');
    END IF;
END
$$;

-- Create bucket_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bucket_status') THEN
        CREATE TYPE bucket_status AS ENUM ('active', 'readonly', 'archived', 'deleted');
    END IF;
END
$$;

-- Create storage_backend enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'storage_backend') THEN
        CREATE TYPE storage_backend AS ENUM ('local', 's3', 'minio', 'gcs');
    END IF;
END
$$;

-- Create hash_algorithm enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'hash_algorithm') THEN
        CREATE TYPE hash_algorithm AS ENUM ('sha256', 'md5', 'xxhash');
    END IF;
END
$$;

-- Create conversion_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'conversion_status') THEN
        CREATE TYPE conversion_status AS ENUM ('pending', 'processing', 'completed', 'failed');
    END IF;
END
$$;

-- Create conversion_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'conversion_type') THEN
        CREATE TYPE conversion_type AS ENUM ('image_to_image', 'document_to_pdf', 'video_to_video', 'audio_to_audio');
    END IF;
END
$$;

-- Create comment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'comment_status') THEN
        CREATE TYPE comment_status AS ENUM ('active', 'resolved', 'deleted', 'archived');
    END IF;
END
$$;

-- Create lock_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lock_status') THEN
        CREATE TYPE lock_status AS ENUM ('active', 'expired', 'released');
    END IF;
END
$$;

-- Create share_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'share_type') THEN
        CREATE TYPE share_type AS ENUM ('user', 'link', 'password');
    END IF;
END
$$;

-- Create share_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'share_status') THEN
        CREATE TYPE share_status AS ENUM ('active', 'expired', 'exhausted', 'revoked');
    END IF;
END
$$;

-- Create share_permission enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'share_permission') THEN
        CREATE TYPE share_permission AS ENUM ('private', 'view', 'edit', 'full');
    END IF;
END
$$;

-- Create version_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'version_type') THEN
        CREATE TYPE version_type AS ENUM ('upload', 'replace', 'edit', 'restore', 'auto_save');
    END IF;
END
$$;

-- Create processing_job_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'processing_job_type') THEN
        CREATE TYPE processing_job_type AS ENUM ('thumbnail_generation', 'video_thumbnail', 'document_preview', 'compression', 'virus_scan', 'deduplication_check');
    END IF;
END
$$;

-- Create job_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_status') THEN
        CREATE TYPE job_status AS ENUM ('pending', 'running', 'completed', 'failed', 'cancelled');
    END IF;
END
$$;

-- Create file_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'file_status') THEN
        CREATE TYPE file_status AS ENUM ('uploading', 'processing', 'active', 'quarantined', 'deleted', 'purged');
    END IF;
END
$$;

-- Create threat_level enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'threat_level') THEN
        CREATE TYPE threat_level AS ENUM ('safe', 'low', 'medium', 'high', 'critical');
    END IF;
END
$$;

-- Create access_action enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'access_action') THEN
        CREATE TYPE access_action AS ENUM ('download', 'view', 'preview');
    END IF;
END
$$;

-- Create processing_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'processing_status') THEN
        CREATE TYPE processing_status AS ENUM ('pending', 'processing', 'thumbnails_ready', 'scan_complete', 'complete', 'failed');
    END IF;
END
$$;

-- Create thumbnail_size enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'thumbnail_size') THEN
        CREATE TYPE thumbnail_size AS ENUM ('tiny', 'small', 'medium', 'large', 'xlarge');
    END IF;
END
$$;

-- Create upload_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'upload_status') THEN
        CREATE TYPE upload_status AS ENUM ('initiated', 'uploading', 'completing', 'completed', 'expired', 'failed');
    END IF;
END
$$;

-- Create quota_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quota_status') THEN
        CREATE TYPE quota_status AS ENUM ('normal', 'exceeded');
    END IF;
END
$$;

