//! Event handler trait for FileLock events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::FileLockEvent;

/// Event handler for FileLock events.
/// Implement this trait to react to FileLock lifecycle events.
pub trait FileLockEventHandler: EventHandler<FileLockEvent> {}
