//! Event handler trait for Thumbnail events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ThumbnailEvent;

/// Event handler for Thumbnail events.
/// Implement this trait to react to Thumbnail lifecycle events.
pub trait ThumbnailEventHandler: EventHandler<ThumbnailEvent> {}
