//! Value Objects
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! DDD Value Objects - immutable types defined by their attributes.

mod timestamps;
mod actors;
mod storage_size;
mod metadata;

// Re-exports
pub use timestamps::Timestamps;
pub use timestamps::TimestampsBuilder;
pub use actors::Actors;
pub use actors::ActorsBuilder;
pub use storage_size::StorageSize;
pub use storage_size::StorageSizeBuilder;
pub use metadata::Metadata;
pub use metadata::MetadataBuilder;
