//! FileComment seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial FileComment data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// FILECOMMENT SEEDER
// ============================================================================

/// Seeder for file_comment
pub struct SeedFileCommentSeeder;

impl SeedFileCommentSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedFileCommentSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedFileCommentSeeder {
    fn name(&self) -> &'static str {
        "SeedFileCommentSeeder"
    }

    fn order(&self) -> i32 {
        13
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if file_comments table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM file_comments")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/file_comment_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM file_comments")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

