//! Repository for StoredFile entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<StoredFile, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::StoredFile;

/// Table name for StoredFile entities
pub const TABLE_NAME: &str = "stored_files";

/// Repository for StoredFile entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct StoredFileRepository(
    backbone_orm::GenericCrudRepository<StoredFile, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for StoredFileRepository {
    type Target = backbone_orm::GenericCrudRepository<StoredFile, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl StoredFileRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(StoredFileRepository, StoredFile, soft_delete);
