//! Validator for ConversionJob entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ConversionJob>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ConversionJob;

/// Validator type alias for ConversionJob entities.
pub type ConversionJobValidator = EntityValidator<ConversionJob>;

/// Build a validator for ConversionJob with all schema-defined field rules.
pub fn conversion_job_validator() -> ConversionJobValidator {
    EntityValidator::new()
        .rule(RequiredString::new("target_format", |e: &ConversionJob| &e.target_format))
        .rule(OptionalNotBlank::new("error_message", |e: &ConversionJob| e.error_message.as_deref()))
    // <<< CUSTOM RULES
    // hook rule: source_file_must_exist (implement in CUSTOM zone)
    // hook rule: source_must_be_accessible (implement in CUSTOM zone)
    // hook rule: valid_target_format (implement in CUSTOM zone)
    // hook rule: conversion_supported (implement in CUSTOM zone)
    // hook rule: sufficient_quota (implement in CUSTOM zone)
    // hook rule: no_duplicate_pending (implement in CUSTOM zone)
    // hook rule: progress_monotonic (implement in CUSTOM zone)
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM