//! Auth configuration for UploadSession handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<UploadSession>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::UploadSessionService;
use crate::domain::entity::UploadSession;

/// Permission string constants for UploadSession operations.
pub mod permissions {
    pub const LIST:        &str = "upload_session:list";
    pub const READ:        &str = "upload_session:read";
    pub const CREATE:      &str = "upload_session:create";
    pub const UPDATE:      &str = "upload_session:update";
    pub const DELETE:      &str = "upload_session:delete";
    pub const RESTORE:     &str = "upload_session:restore";
    pub const TRASH:       &str = "upload_session:trash";
    pub const EMPTY_TRASH: &str = "upload_session:empty_trash";
    pub const BULK_CREATE: &str = "upload_session:bulk_create";
    pub const UPSERT:      &str = "upload_session:upsert";
}

/// Resource policy for UploadSession — maps CRUD actions to permission strings.
pub struct UploadSessionPolicy;

#[async_trait]
impl ResourcePolicy<UploadSession> for UploadSessionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &UploadSession,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for UploadSession handlers.
///
/// Wraps `UploadSessionService` and checks `UploadSessionPolicy` before delegating.
pub type UploadSessionGuard = PermissionGuard<UploadSession, UploadSessionService, UploadSessionPolicy>;

/// Service-integrated permission guard for UploadSession (for use in generated handlers).
pub type UploadSessionServiceGuard = ServicePermissionGuard<UploadSession, UploadSessionService, UploadSessionPolicy>;

// <<< CUSTOM
// END CUSTOM
