//! AccessLog API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the AccessLog CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ACCESSLOG TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AccessLog
pub struct AccessLogTestData;

impl TestDataGenerator for AccessLogTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "file_id": null,
            "bucket_id": null,
            "action": null,
            "user_id": null,
            "share_id": null,
            "is_owner": false,
            "is_shared": false,
            "is_public": false,
            "ip_address": null,
            "user_agent": null,
            "referer": null,
            "country_code": null,
            "city": null,
            "bytes_transferred": null,
            "duration_ms": null,
            "success": null,
            "error_message": null,
            "accessed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "file_id": null,
            "bucket_id": null,
            "action": null,
            "user_id": null,
            "share_id": null,
            "is_owner": false,
            "is_shared": false,
            "is_public": false,
            "ip_address": null,
            "user_agent": null,
            "referer": null,
            "country_code": null,
            "city": null,
            "bytes_transferred": null,
            "duration_ms": null,
            "success": null,
            "error_message": null,
            "accessed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ACCESSLOG API TEST
// ============================================================================

/// AccessLog API test suite
pub struct AccessLogApiTest {
    inner: GenericCrudTest<AccessLogTestData>,
}

impl AccessLogApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/access_logs", "AccessLog");
        Self {
            inner: GenericCrudTest::new(config, AccessLogTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AccessLogApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_access_log_crud() {
        let mut test = AccessLogApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AccessLog specific tests here
// <<< CUSTOM TESTS END >>>
