//! UserQuota API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the UserQuota CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// USERQUOTA TEST DATA GENERATOR
// ============================================================================

/// Test data generator for UserQuota
pub struct UserQuotaTestData;

impl TestDataGenerator for UserQuotaTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "user_id": null,
            "limit_bytes": null,
            "used_bytes": null,
            "file_count": null,
            "max_file_size": null,
            "max_file_count": null,
            "tier": null,
            "quota_status": null,
            "warning_threshold_percent": null,
            "last_warning_sent_at": now,
            "peak_usage_bytes": null,
            "peak_usage_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "user_id": null,
            "limit_bytes": null,
            "used_bytes": null,
            "file_count": null,
            "max_file_size": null,
            "max_file_count": null,
            "tier": null,
            "quota_status": null,
            "warning_threshold_percent": null,
            "last_warning_sent_at": now,
            "peak_usage_bytes": null,
            "peak_usage_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// USERQUOTA API TEST
// ============================================================================

/// UserQuota API test suite
pub struct UserQuotaApiTest {
    inner: GenericCrudTest<UserQuotaTestData>,
}

impl UserQuotaApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/user_quotas", "UserQuota");
        Self {
            inner: GenericCrudTest::new(config, UserQuotaTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for UserQuotaApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_user_quota_crud() {
        let mut test = UserQuotaApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add UserQuota specific tests here
// <<< CUSTOM TESTS END >>>
