//! ConversionJob Projector (Event Handler)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This projector listens to domain events and updates the projection.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use chrono::Utc;

use super::ConversionJobProjection;
use crate::domain::entity::ConversionJob;
use crate::domain::events::{
    ConversionJobCreatedEvent, ConversionJobUpdatedEvent, ConversionJobDeletedEvent,
};

// ============================================================================
// EVENT HANDLER TRAIT
// ============================================================================

/// Trait for handling ConversionJob domain events
///
/// All handler methods receive the event sequence number for tracking
/// which events have been processed by the projector.
#[async_trait]
pub trait ConversionJobEventHandler: Send + Sync {
    /// Handle entity created event
    async fn on_created(&self, event: ConversionJobCreatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity updated event
    async fn on_updated(&self, event: ConversionJobUpdatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity deleted event
    async fn on_deleted(&self, event: ConversionJobDeletedEvent, sequence: i64) -> Result<()>;
}

// ============================================================================
// PROJECTION REPOSITORY
// ============================================================================

/// Repository for ConversionJob projections
#[async_trait]
pub trait ConversionJobProjectionRepository: Send + Sync {
    async fn save(&self, projection: &ConversionJobProjection) -> Result<()>;
    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<ConversionJobProjection>>;
    async fn delete(&self, id: uuid::Uuid) -> Result<()>;
    async fn rebuild_all(&self) -> Result<u64>;
}

// ============================================================================
// PROJECTOR
// ============================================================================

/// Projector that updates ConversionJob projection from events
pub struct ConversionJobProjector<R: ConversionJobProjectionRepository> {
    repository: Arc<R>,
}

impl<R: ConversionJobProjectionRepository> ConversionJobProjector<R> {
    /// Create a new projector
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }

    /// Rebuild all projections from event history
    pub async fn rebuild(&self) -> Result<u64> {
        self.repository.rebuild_all().await
    }

    /// Process a stored event from the event store
    ///
    /// This method dispatches the event to the appropriate handler based on event type.
    /// Returns Ok(true) if the event was processed, Ok(false) if it was skipped.
    pub async fn process_stored_event(&self, event: &crate::infrastructure::event_store::StoredEvent) -> Result<bool>
    where
        Self: ConversionJobEventHandler,
    {
        let sequence = event.sequence;

        match event.event_type.as_str() {
            "ConversionJobCreatedEvent" => {
                let created: ConversionJobCreatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_created(created, sequence).await?;
                Ok(true)
            }
            "ConversionJobUpdatedEvent" => {
                let updated: ConversionJobUpdatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_updated(updated, sequence).await?;
                Ok(true)
            }
            "ConversionJobDeletedEvent" => {
                let deleted: ConversionJobDeletedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_deleted(deleted, sequence).await?;
                Ok(true)
            }
            _ => Ok(false), // Event type not handled by this projector
        }
    }
}

#[async_trait]
impl<R: ConversionJobProjectionRepository> ConversionJobEventHandler for ConversionJobProjector<R> {

    async fn on_created(&self, event: ConversionJobCreatedEvent, sequence: i64) -> Result<()> {
        let mut projection = ConversionJobProjection::new(
            event.id,
            event.source_file_id,
            event.target_format,
            event.status,
            event.conversion_options,
            event.result_file_id,
            event.progress,
            event.error_message,
            event.started_at,
            event.completed_at,
            event.metadata
        );

        // Track the event sequence for this projection
        projection.apply_event(sequence);

        self.repository.save(&projection).await
    }

    async fn on_updated(&self, event: ConversionJobUpdatedEvent, sequence: i64) -> Result<()> {
        if let Some(mut projection) = self.repository.find_by_id(event.id).await? {
            // Apply updates from event
            projection.source_file_id = event.source_file_id;
            projection.target_format = event.target_format;
            projection.status = event.status;
            projection.conversion_options = event.conversion_options;
            projection.result_file_id = event.result_file_id;
            projection.progress = event.progress;
            projection.error_message = event.error_message;
            projection.started_at = event.started_at;
            projection.completed_at = event.completed_at;
            projection.metadata = event.metadata;
            // Track the event sequence for this projection
            projection.apply_event(sequence);

            self.repository.save(&projection).await?;
        }

        Ok(())
    }

    async fn on_deleted(&self, event: ConversionJobDeletedEvent, _sequence: i64) -> Result<()> {
        self.repository.delete(event.id).await
    }
}

// ============================================================================
// CUSTOM EVENT HANDLERS
// ============================================================================
// <<< CUSTOM HANDLERS START >>>

// <<< CUSTOM HANDLERS START >>>
// Add custom event handlers here
// <<< CUSTOM HANDLERS END >>>