//! FileComment Projector (Event Handler)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This projector listens to domain events and updates the projection.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use chrono::Utc;

use super::FileCommentProjection;
use crate::domain::entity::FileComment;
use crate::domain::events::{
    FileCommentCreatedEvent, FileCommentUpdatedEvent, FileCommentDeletedEvent,
};

// ============================================================================
// EVENT HANDLER TRAIT
// ============================================================================

/// Trait for handling FileComment domain events
///
/// All handler methods receive the event sequence number for tracking
/// which events have been processed by the projector.
#[async_trait]
pub trait FileCommentEventHandler: Send + Sync {
    /// Handle entity created event
    async fn on_created(&self, event: FileCommentCreatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity updated event
    async fn on_updated(&self, event: FileCommentUpdatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity deleted event
    async fn on_deleted(&self, event: FileCommentDeletedEvent, sequence: i64) -> Result<()>;
}

// ============================================================================
// PROJECTION REPOSITORY
// ============================================================================

/// Repository for FileComment projections
#[async_trait]
pub trait FileCommentProjectionRepository: Send + Sync {
    async fn save(&self, projection: &FileCommentProjection) -> Result<()>;
    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<FileCommentProjection>>;
    async fn delete(&self, id: uuid::Uuid) -> Result<()>;
    async fn rebuild_all(&self) -> Result<u64>;
}

// ============================================================================
// PROJECTOR
// ============================================================================

/// Projector that updates FileComment projection from events
pub struct FileCommentProjector<R: FileCommentProjectionRepository> {
    repository: Arc<R>,
}

impl<R: FileCommentProjectionRepository> FileCommentProjector<R> {
    /// Create a new projector
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }

    /// Rebuild all projections from event history
    pub async fn rebuild(&self) -> Result<u64> {
        self.repository.rebuild_all().await
    }

    /// Process a stored event from the event store
    ///
    /// This method dispatches the event to the appropriate handler based on event type.
    /// Returns Ok(true) if the event was processed, Ok(false) if it was skipped.
    pub async fn process_stored_event(&self, event: &crate::infrastructure::event_store::StoredEvent) -> Result<bool>
    where
        Self: FileCommentEventHandler,
    {
        let sequence = event.sequence;

        match event.event_type.as_str() {
            "FileCommentCreatedEvent" => {
                let created: FileCommentCreatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_created(created, sequence).await?;
                Ok(true)
            }
            "FileCommentUpdatedEvent" => {
                let updated: FileCommentUpdatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_updated(updated, sequence).await?;
                Ok(true)
            }
            "FileCommentDeletedEvent" => {
                let deleted: FileCommentDeletedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_deleted(deleted, sequence).await?;
                Ok(true)
            }
            _ => Ok(false), // Event type not handled by this projector
        }
    }
}

#[async_trait]
impl<R: FileCommentProjectionRepository> FileCommentEventHandler for FileCommentProjector<R> {

    async fn on_created(&self, event: FileCommentCreatedEvent, sequence: i64) -> Result<()> {
        let mut projection = FileCommentProjection::new(
            event.id,
            event.file_id,
            event.user_id,
            event.parent_id,
            event.content,
            event.annotation_region,
            event.mentions,
            event.resolved,
            event.resolved_by,
            event.resolved_at,
            event.status,
            event.metadata
        );

        // Track the event sequence for this projection
        projection.apply_event(sequence);

        self.repository.save(&projection).await
    }

    async fn on_updated(&self, event: FileCommentUpdatedEvent, sequence: i64) -> Result<()> {
        if let Some(mut projection) = self.repository.find_by_id(event.id).await? {
            // Apply updates from event
            projection.file_id = event.file_id;
            projection.user_id = event.user_id;
            projection.parent_id = event.parent_id;
            projection.content = event.content;
            projection.annotation_region = event.annotation_region;
            projection.mentions = event.mentions;
            projection.resolved = event.resolved;
            projection.resolved_by = event.resolved_by;
            projection.resolved_at = event.resolved_at;
            projection.status = event.status;
            projection.metadata = event.metadata;
            // Track the event sequence for this projection
            projection.apply_event(sequence);

            self.repository.save(&projection).await?;
        }

        Ok(())
    }

    async fn on_deleted(&self, event: FileCommentDeletedEvent, _sequence: i64) -> Result<()> {
        self.repository.delete(event.id).await
    }
}

// ============================================================================
// CUSTOM EVENT HANDLERS
// ============================================================================
// <<< CUSTOM HANDLERS START >>>

// <<< CUSTOM HANDLERS START >>>
// Add custom event handlers here
// <<< CUSTOM HANDLERS END >>>