//! FileAccessLog Projector (Event Handler)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This projector listens to domain events and updates the projection.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use chrono::Utc;

use super::FileAccessLogProjection;
use crate::domain::entity::FileAccessLog;
use crate::domain::events::{
    FileAccessLogCreatedEvent, FileAccessLogUpdatedEvent, FileAccessLogDeletedEvent,
};

// ============================================================================
// EVENT HANDLER TRAIT
// ============================================================================

/// Trait for handling FileAccessLog domain events
///
/// All handler methods receive the event sequence number for tracking
/// which events have been processed by the projector.
#[async_trait]
pub trait FileAccessLogEventHandler: Send + Sync {
    /// Handle entity created event
    async fn on_created(&self, event: FileAccessLogCreatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity updated event
    async fn on_updated(&self, event: FileAccessLogUpdatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity deleted event
    async fn on_deleted(&self, event: FileAccessLogDeletedEvent, sequence: i64) -> Result<()>;
}

// ============================================================================
// PROJECTION REPOSITORY
// ============================================================================

/// Repository for FileAccessLog projections
#[async_trait]
pub trait FileAccessLogProjectionRepository: Send + Sync {
    async fn save(&self, projection: &FileAccessLogProjection) -> Result<()>;
    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<FileAccessLogProjection>>;
    async fn delete(&self, id: uuid::Uuid) -> Result<()>;
    async fn rebuild_all(&self) -> Result<u64>;
}

// ============================================================================
// PROJECTOR
// ============================================================================

/// Projector that updates FileAccessLog projection from events
pub struct FileAccessLogProjector<R: FileAccessLogProjectionRepository> {
    repository: Arc<R>,
}

impl<R: FileAccessLogProjectionRepository> FileAccessLogProjector<R> {
    /// Create a new projector
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }

    /// Rebuild all projections from event history
    pub async fn rebuild(&self) -> Result<u64> {
        self.repository.rebuild_all().await
    }

    /// Process a stored event from the event store
    ///
    /// This method dispatches the event to the appropriate handler based on event type.
    /// Returns Ok(true) if the event was processed, Ok(false) if it was skipped.
    pub async fn process_stored_event(&self, event: &crate::infrastructure::event_store::StoredEvent) -> Result<bool>
    where
        Self: FileAccessLogEventHandler,
    {
        let sequence = event.sequence;

        match event.event_type.as_str() {
            "FileAccessLogCreatedEvent" => {
                let created: FileAccessLogCreatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_created(created, sequence).await?;
                Ok(true)
            }
            "FileAccessLogUpdatedEvent" => {
                let updated: FileAccessLogUpdatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_updated(updated, sequence).await?;
                Ok(true)
            }
            "FileAccessLogDeletedEvent" => {
                let deleted: FileAccessLogDeletedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_deleted(deleted, sequence).await?;
                Ok(true)
            }
            _ => Ok(false), // Event type not handled by this projector
        }
    }
}

#[async_trait]
impl<R: FileAccessLogProjectionRepository> FileAccessLogEventHandler for FileAccessLogProjector<R> {

    async fn on_created(&self, event: FileAccessLogCreatedEvent, sequence: i64) -> Result<()> {
        let mut projection = FileAccessLogProjection::new(
            event.id,
            event.file_id,
            event.user_id,
            event.share_id,
            event.action,
            event.ip_address,
            event.user_agent,
            event.accessed_at
        );

        // Track the event sequence for this projection
        projection.apply_event(sequence);

        self.repository.save(&projection).await
    }

    async fn on_updated(&self, event: FileAccessLogUpdatedEvent, sequence: i64) -> Result<()> {
        if let Some(mut projection) = self.repository.find_by_id(event.id).await? {
            // Apply updates from event
            projection.file_id = event.file_id;
            projection.user_id = event.user_id;
            projection.share_id = event.share_id;
            projection.action = event.action;
            projection.ip_address = event.ip_address;
            projection.user_agent = event.user_agent;
            projection.accessed_at = event.accessed_at;
            // Track the event sequence for this projection
            projection.apply_event(sequence);

            self.repository.save(&projection).await?;
        }

        Ok(())
    }

    async fn on_deleted(&self, event: FileAccessLogDeletedEvent, _sequence: i64) -> Result<()> {
        self.repository.delete(event.id).await
    }
}

// ============================================================================
// CUSTOM EVENT HANDLERS
// ============================================================================

// <<< CUSTOM HANDLERS START >>>
// Add custom event handlers here
// <<< CUSTOM HANDLERS END >>>
