//! FileVersion Projector (Event Handler)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This projector listens to domain events and updates the projection.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use chrono::Utc;

use super::FileVersionProjection;
use crate::domain::entity::FileVersion;
use crate::domain::events::{
    FileVersionCreatedEvent, FileVersionUpdatedEvent, FileVersionDeletedEvent,
};

// ============================================================================
// EVENT HANDLER TRAIT
// ============================================================================

/// Trait for handling FileVersion domain events
///
/// All handler methods receive the event sequence number for tracking
/// which events have been processed by the projector.
#[async_trait]
pub trait FileVersionEventHandler: Send + Sync {
    /// Handle entity created event
    async fn on_created(&self, event: FileVersionCreatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity updated event
    async fn on_updated(&self, event: FileVersionUpdatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity deleted event
    async fn on_deleted(&self, event: FileVersionDeletedEvent, sequence: i64) -> Result<()>;
}

// ============================================================================
// PROJECTION REPOSITORY
// ============================================================================

/// Repository for FileVersion projections
#[async_trait]
pub trait FileVersionProjectionRepository: Send + Sync {
    async fn save(&self, projection: &FileVersionProjection) -> Result<()>;
    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<FileVersionProjection>>;
    async fn delete(&self, id: uuid::Uuid) -> Result<()>;
    async fn rebuild_all(&self) -> Result<u64>;
}

// ============================================================================
// PROJECTOR
// ============================================================================

/// Projector that updates FileVersion projection from events
pub struct FileVersionProjector<R: FileVersionProjectionRepository> {
    repository: Arc<R>,
}

impl<R: FileVersionProjectionRepository> FileVersionProjector<R> {
    /// Create a new projector
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }

    /// Rebuild all projections from event history
    pub async fn rebuild(&self) -> Result<u64> {
        self.repository.rebuild_all().await
    }

    /// Process a stored event from the event store
    ///
    /// This method dispatches the event to the appropriate handler based on event type.
    /// Returns Ok(true) if the event was processed, Ok(false) if it was skipped.
    pub async fn process_stored_event(&self, event: &crate::infrastructure::event_store::StoredEvent) -> Result<bool>
    where
        Self: FileVersionEventHandler,
    {
        let sequence = event.sequence;

        match event.event_type.as_str() {
            "FileVersionCreatedEvent" => {
                let created: FileVersionCreatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_created(created, sequence).await?;
                Ok(true)
            }
            "FileVersionUpdatedEvent" => {
                let updated: FileVersionUpdatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_updated(updated, sequence).await?;
                Ok(true)
            }
            "FileVersionDeletedEvent" => {
                let deleted: FileVersionDeletedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_deleted(deleted, sequence).await?;
                Ok(true)
            }
            _ => Ok(false), // Event type not handled by this projector
        }
    }
}

#[async_trait]
impl<R: FileVersionProjectionRepository> FileVersionEventHandler for FileVersionProjector<R> {

    async fn on_created(&self, event: FileVersionCreatedEvent, sequence: i64) -> Result<()> {
        let mut projection = FileVersionProjection::new(
            event.id,
            event.file_id,
            event.version_number,
            event.version_type,
            event.storage_key,
            event.storage_backend,
            event.name,
            event.mime_type,
            event.checksum_md5,
            event.checksum_sha256,
            event.created_by_id,
            event.change_summary,
            event.is_current,
            event.restored_from_id,
            event.expires_at,
            event.is_deleted,
            event.deleted_at,
            event.size_bytes,
            event.metadata
        );

        // Track the event sequence for this projection
        projection.apply_event(sequence);

        self.repository.save(&projection).await
    }

    async fn on_updated(&self, event: FileVersionUpdatedEvent, sequence: i64) -> Result<()> {
        if let Some(mut projection) = self.repository.find_by_id(event.id).await? {
            // Apply updates from event
            projection.file_id = event.file_id;
            projection.version_number = event.version_number;
            projection.version_type = event.version_type;
            projection.storage_key = event.storage_key;
            projection.storage_backend = event.storage_backend;
            projection.name = event.name;
            projection.mime_type = event.mime_type;
            projection.checksum_md5 = event.checksum_md5;
            projection.checksum_sha256 = event.checksum_sha256;
            projection.created_by_id = event.created_by_id;
            projection.change_summary = event.change_summary;
            projection.is_current = event.is_current;
            projection.restored_from_id = event.restored_from_id;
            projection.expires_at = event.expires_at;
            projection.is_deleted = event.is_deleted;
            projection.deleted_at = event.deleted_at;
            projection.size_bytes = event.size_bytes;
            projection.metadata = event.metadata;
            // Track the event sequence for this projection
            projection.apply_event(sequence);

            self.repository.save(&projection).await?;
        }

        Ok(())
    }

    async fn on_deleted(&self, event: FileVersionDeletedEvent, _sequence: i64) -> Result<()> {
        self.repository.delete(event.id).await
    }
}

// ============================================================================
// CUSTOM EVENT HANDLERS
// ============================================================================
// <<< CUSTOM HANDLERS START >>>

// <<< CUSTOM HANDLERS START >>>
// Add custom event handlers here
// <<< CUSTOM HANDLERS END >>>