//! FileVersion Projection (Read Model)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This is a CQRS projection - an optimized read model for queries.
//! It is updated asynchronously from domain events.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

// ============================================================================
// PROJECTION (READ MODEL)
// ============================================================================

/// FileVersion read model optimized for queries
///
/// This projection is denormalized for fast reads.
/// It is updated when domain events are published.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct FileVersionProjection {
    pub id: Uuid,
    pub file_id: Uuid,
    pub version_number: i32,
    pub version_type: VersionType,
    pub storage_key: String,
    pub storage_backend: String,
    pub name: String,
    pub mime_type: String,
    pub checksum_md5: Option<String>,
    pub checksum_sha256: Option<String>,
    pub created_by_id: Uuid,
    pub change_summary: Option<String>,
    pub is_current: bool,
    pub restored_from_id: Option<Uuid>,
    pub expires_at: Option<DateTime<Utc>>,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTime<Utc>>,
    pub size_bytes: i64,
    pub metadata: serde_json::Value,

    // Projection metadata
    /// Version of the projection (for optimistic locking)
    pub projection_version: i64,
    /// Last event sequence number applied
    pub last_event_sequence: i64,
    /// When this projection was last updated
    pub projection_updated_at: DateTime<Utc>,
}

impl FileVersionProjection {
    /// Create a new projection from entity data
    pub fn new(
        id: Uuid,
        file_id: Uuid,
        version_number: i32,
        version_type: VersionType,
        storage_key: String,
        storage_backend: String,
        name: String,
        mime_type: String,
        checksum_md5: Option<String>,
        checksum_sha256: Option<String>,
        created_by_id: Uuid,
        change_summary: Option<String>,
        is_current: bool,
        restored_from_id: Option<Uuid>,
        expires_at: Option<DateTime<Utc>>,
        is_deleted: bool,
        deleted_at: Option<DateTime<Utc>>,
        size_bytes: i64,
        metadata: serde_json::Value
    ) -> Self {
        Self {
            id,
            file_id,
            version_number,
            version_type,
            storage_key,
            storage_backend,
            name,
            mime_type,
            checksum_md5,
            checksum_sha256,
            created_by_id,
            change_summary,
            is_current,
            restored_from_id,
            expires_at,
            is_deleted,
            deleted_at,
            size_bytes,
            metadata,
            projection_version: 1,
            last_event_sequence: 0,
            projection_updated_at: Utc::now(),
        }
    }

    /// Get the projection ID
    pub fn id(&self) -> &Uuid {
        &self.id
    }

    /// Update projection version after applying event
    pub fn apply_event(&mut self, event_sequence: i64) {
        self.projection_version += 1;
        self.last_event_sequence = event_sequence;
        self.projection_updated_at = Utc::now();
    }
}

// ============================================================================
// SUMMARY PROJECTION (LIST VIEW)
// ============================================================================

/// Summary view of FileVersion for list displays
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct FileVersionSummary {
    pub id: Uuid,
    pub name: String,
}

// ============================================================================
// CUSTOM PROJECTIONS
// ============================================================================
// <<< CUSTOM PROJECTIONS START >>>

// <<< CUSTOM PROJECTIONS START >>>
// Add custom read models here for specific query use cases
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct FileVersionDashboard {
//     pub id: Uuid,
//     pub key_metric: i64,
// }
// <<< CUSTOM PROJECTIONS END >>>