//! UploadSession Projector (Event Handler)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This projector listens to domain events and updates the projection.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use chrono::Utc;

use super::UploadSessionProjection;
use crate::domain::entity::UploadSession;
use crate::domain::events::{
    UploadSessionCreatedEvent, UploadSessionUpdatedEvent, UploadSessionDeletedEvent,
};

// ============================================================================
// EVENT HANDLER TRAIT
// ============================================================================

/// Trait for handling UploadSession domain events
///
/// All handler methods receive the event sequence number for tracking
/// which events have been processed by the projector.
#[async_trait]
pub trait UploadSessionEventHandler: Send + Sync {
    /// Handle entity created event
    async fn on_created(&self, event: UploadSessionCreatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity updated event
    async fn on_updated(&self, event: UploadSessionUpdatedEvent, sequence: i64) -> Result<()>;
    /// Handle entity deleted event
    async fn on_deleted(&self, event: UploadSessionDeletedEvent, sequence: i64) -> Result<()>;
}

// ============================================================================
// PROJECTION REPOSITORY
// ============================================================================

/// Repository for UploadSession projections
#[async_trait]
pub trait UploadSessionProjectionRepository: Send + Sync {
    async fn save(&self, projection: &UploadSessionProjection) -> Result<()>;
    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<UploadSessionProjection>>;
    async fn delete(&self, id: uuid::Uuid) -> Result<()>;
    async fn rebuild_all(&self) -> Result<u64>;
}

// ============================================================================
// PROJECTOR
// ============================================================================

/// Projector that updates UploadSession projection from events
pub struct UploadSessionProjector<R: UploadSessionProjectionRepository> {
    repository: Arc<R>,
}

impl<R: UploadSessionProjectionRepository> UploadSessionProjector<R> {
    /// Create a new projector
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }

    /// Rebuild all projections from event history
    pub async fn rebuild(&self) -> Result<u64> {
        self.repository.rebuild_all().await
    }

    /// Process a stored event from the event store
    ///
    /// This method dispatches the event to the appropriate handler based on event type.
    /// Returns Ok(true) if the event was processed, Ok(false) if it was skipped.
    pub async fn process_stored_event(&self, event: &crate::infrastructure::event_store::StoredEvent) -> Result<bool>
    where
        Self: UploadSessionEventHandler,
    {
        let sequence = event.sequence;

        match event.event_type.as_str() {
            "UploadSessionCreatedEvent" => {
                let created: UploadSessionCreatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_created(created, sequence).await?;
                Ok(true)
            }
            "UploadSessionUpdatedEvent" => {
                let updated: UploadSessionUpdatedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_updated(updated, sequence).await?;
                Ok(true)
            }
            "UploadSessionDeletedEvent" => {
                let deleted: UploadSessionDeletedEvent = serde_json::from_value(event.payload.clone())?;
                self.on_deleted(deleted, sequence).await?;
                Ok(true)
            }
            _ => Ok(false), // Event type not handled by this projector
        }
    }
}

#[async_trait]
impl<R: UploadSessionProjectionRepository> UploadSessionEventHandler for UploadSessionProjector<R> {

    async fn on_created(&self, event: UploadSessionCreatedEvent, sequence: i64) -> Result<()> {
        let mut projection = UploadSessionProjection::new(
            event.id,
            event.bucket_id,
            event.user_id,
            event.path,
            event.filename,
            event.mime_type,
            event.file_size,
            event.chunk_size,
            event.total_chunks,
            event.uploaded_chunks,
            event.status,
            event.storage_backend,
            event.completed_parts,
            event.part_etags,
            event.expires_at,
            event.metadata
        );

        // Track the event sequence for this projection
        projection.apply_event(sequence);

        self.repository.save(&projection).await
    }

    async fn on_updated(&self, event: UploadSessionUpdatedEvent, sequence: i64) -> Result<()> {
        if let Some(mut projection) = self.repository.find_by_id(event.id).await? {
            // Apply updates from event
            projection.bucket_id = event.bucket_id;
            projection.user_id = event.user_id;
            projection.path = event.path;
            projection.filename = event.filename;
            projection.mime_type = event.mime_type;
            projection.file_size = event.file_size;
            projection.chunk_size = event.chunk_size;
            projection.total_chunks = event.total_chunks;
            projection.uploaded_chunks = event.uploaded_chunks;
            projection.status = event.status;
            projection.storage_backend = event.storage_backend;
            projection.completed_parts = event.completed_parts;
            projection.part_etags = event.part_etags;
            projection.expires_at = event.expires_at;
            projection.metadata = event.metadata;
            // Track the event sequence for this projection
            projection.apply_event(sequence);

            self.repository.save(&projection).await?;
        }

        Ok(())
    }

    async fn on_deleted(&self, event: UploadSessionDeletedEvent, _sequence: i64) -> Result<()> {
        self.repository.delete(event.id).await
    }
}

// ============================================================================
// CUSTOM EVENT HANDLERS
// ============================================================================
// <<< CUSTOM HANDLERS START >>>

// <<< CUSTOM HANDLERS START >>>
// Add custom event handlers here
// <<< CUSTOM HANDLERS END >>>