//! FileProcessing flow implementation
//!
//! Generated by backbone-schema
//!
//! Async file processing workflow including:
//! - Image thumbnail generation
//! - Video thumbnail generation
//! - Document preview generation
//! - File compression
//! - Virus scanning
//! - Content deduplication checking
//! - CDN URL generation

use std::sync::Arc;
use serde::{Deserialize, Serialize};
use backbone_core::flow::{FlowError, FlowStatus, FlowInstance, FlowExecutor};


pub type FileProcessingFlowStatus = FlowStatus;

/// Steps in FileProcessing flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileProcessingFlowStep {
    /// load_job
    LoadJob,
    /// mark_running
    MarkRunning,
    /// load_file
    LoadFile,
    /// load_bucket
    LoadBucket,
    /// route_by_job_type
    RouteByJobType,
    /// process_image_thumbnail
    ProcessImageThumbnail,
    /// store_image_thumbnail
    StoreImageThumbnail,
    /// update_file_thumbnail
    UpdateFileThumbnail,
    /// process_video_thumbnail
    ProcessVideoThumbnail,
    /// store_video_thumbnail
    StoreVideoThumbnail,
    /// update_file_video_thumbnail
    UpdateFileVideoThumbnail,
    /// process_document_preview
    ProcessDocumentPreview,
    /// store_document_preview
    StoreDocumentPreview,
    /// update_file_document_preview
    UpdateFileDocumentPreview,
    /// process_compression
    ProcessCompression,
    /// store_compressed_file
    StoreCompressedFile,
    /// update_file_compression
    UpdateFileCompression,
    /// update_bucket_compression_stats
    UpdateBucketCompressionStats,
    /// process_virus_scan
    ProcessVirusScan,
    /// check_threat_level
    CheckThreatLevel,
    /// update_scan_safe
    UpdateScanSafe,
    /// update_scan_warning
    UpdateScanWarning,
    /// notify_scan_warning
    NotifyScanWarning,
    /// update_scan_threat
    UpdateScanThreat,
    /// notify_threat_detected
    NotifyThreatDetected,
    /// process_deduplication
    ProcessDeduplication,
    /// check_existing_hash
    CheckExistingHash,
    /// update_existing_hash
    UpdateExistingHash,
    /// link_file_hash
    LinkFileHash,
    /// create_new_hash
    CreateNewHash,
    /// mark_complete
    MarkComplete,
    /// emit_complete_event
    EmitCompleteEvent,
    /// complete
    Complete,
    /// retry_or_fail
    RetryOrFail,
    /// schedule_retry
    ScheduleRetry,
    /// retry_terminal
    RetryTerminal,
    /// mark_failed
    MarkFailed,
    /// emit_failed_event
    EmitFailedEvent,
    /// failed_terminal
    FailedTerminal,
    /// job_not_found
    JobNotFound,
    /// file_not_found
    FileNotFound,
    /// unknown_job_type
    UnknownJobType,
}

pub type FileProcessingFlowInstance = FlowInstance<FileProcessingFlowStep>;

/// Step handler trait for FileProcessing flow
#[async_trait::async_trait]
pub trait FileProcessingStepHandler: Send + Sync {
    /// Handle load_job step
    async fn handle_load_job(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle mark_running step
    async fn handle_mark_running(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle load_file step
    async fn handle_load_file(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle load_bucket step
    async fn handle_load_bucket(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Evaluate condition for route_by_job_type step
    async fn evaluate_route_by_job_type(
        &self,
        instance: &FileProcessingFlowInstance,
    ) -> Result<FileProcessingFlowStep, FlowError>;

    /// Handle process_image_thumbnail step
    async fn handle_process_image_thumbnail(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle store_image_thumbnail step
    async fn handle_store_image_thumbnail(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_file_thumbnail step
    async fn handle_update_file_thumbnail(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle process_video_thumbnail step
    async fn handle_process_video_thumbnail(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle store_video_thumbnail step
    async fn handle_store_video_thumbnail(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_file_video_thumbnail step
    async fn handle_update_file_video_thumbnail(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle process_document_preview step
    async fn handle_process_document_preview(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle store_document_preview step
    async fn handle_store_document_preview(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_file_document_preview step
    async fn handle_update_file_document_preview(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle process_compression step
    async fn handle_process_compression(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle store_compressed_file step
    async fn handle_store_compressed_file(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_file_compression step
    async fn handle_update_file_compression(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_bucket_compression_stats step
    async fn handle_update_bucket_compression_stats(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle process_virus_scan step
    async fn handle_process_virus_scan(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Evaluate condition for check_threat_level step
    async fn evaluate_check_threat_level(
        &self,
        instance: &FileProcessingFlowInstance,
    ) -> Result<FileProcessingFlowStep, FlowError>;

    /// Handle update_scan_safe step
    async fn handle_update_scan_safe(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_scan_warning step
    async fn handle_update_scan_warning(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle notify_scan_warning step
    async fn handle_notify_scan_warning(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_scan_threat step
    async fn handle_update_scan_threat(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle notify_threat_detected step
    async fn handle_notify_threat_detected(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle process_deduplication step
    async fn handle_process_deduplication(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle check_existing_hash step
    async fn handle_check_existing_hash(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle update_existing_hash step
    async fn handle_update_existing_hash(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle link_file_hash step
    async fn handle_link_file_hash(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle create_new_hash step
    async fn handle_create_new_hash(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle mark_complete step
    async fn handle_mark_complete(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle emit_complete_event step
    async fn handle_emit_complete_event(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle terminal step complete
    async fn handle_complete(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Evaluate condition for retry_or_fail step
    async fn evaluate_retry_or_fail(
        &self,
        instance: &FileProcessingFlowInstance,
    ) -> Result<FileProcessingFlowStep, FlowError>;

    /// Handle schedule_retry step
    async fn handle_schedule_retry(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle terminal step retry_terminal
    async fn handle_retry_terminal(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle mark_failed step
    async fn handle_mark_failed(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle emit_failed_event step
    async fn handle_emit_failed_event(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<Option<FileProcessingFlowStep>, FlowError>;

    /// Handle terminal step failed_terminal
    async fn handle_failed_terminal(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step job_not_found
    async fn handle_job_not_found(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step file_not_found
    async fn handle_file_not_found(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step unknown_job_type
    async fn handle_unknown_job_type(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Execute compensation (rollback)
    async fn compensate(
        &self,
        instance: &mut FileProcessingFlowInstance,
    ) -> Result<(), FlowError>;

}

/// Executor for FileProcessing flow
pub struct FileProcessingFlowExecutor<H: FileProcessingStepHandler>(FlowExecutor<H>);

impl<H: FileProcessingStepHandler + Send + Sync + 'static> FileProcessingFlowExecutor<H> {
    /// Create a new flow executor
    pub fn new(handler: Arc<H>) -> Self {
        Self(FlowExecutor::new(handler))
    }

    /// Start a new flow instance
    pub fn start(&self, instance_id: impl Into<String>) -> FileProcessingFlowInstance {
        self.0.start(instance_id, FileProcessingFlowStep::LoadJob)
    }

    /// Execute the current step
    pub async fn execute_step(&self, instance: &mut FileProcessingFlowInstance) -> Result<(), FlowError> {
        let current_step = match instance.current_step {
            Some(step) => step,
            None => return Err(FlowError::NoCurrentStep),
        };

        let next_step = match current_step {
            FileProcessingFlowStep::LoadJob => {
                self.0.handler.handle_load_job(instance).await?
            }
            FileProcessingFlowStep::MarkRunning => {
                self.0.handler.handle_mark_running(instance).await?
            }
            FileProcessingFlowStep::LoadFile => {
                self.0.handler.handle_load_file(instance).await?
            }
            FileProcessingFlowStep::LoadBucket => {
                self.0.handler.handle_load_bucket(instance).await?
            }
            FileProcessingFlowStep::RouteByJobType => {
                let next = self.0.handler.evaluate_route_by_job_type(instance).await?;
                Some(next)
            }
            FileProcessingFlowStep::ProcessImageThumbnail => {
                self.0.handler.handle_process_image_thumbnail(instance).await?
            }
            FileProcessingFlowStep::StoreImageThumbnail => {
                self.0.handler.handle_store_image_thumbnail(instance).await?
            }
            FileProcessingFlowStep::UpdateFileThumbnail => {
                self.0.handler.handle_update_file_thumbnail(instance).await?
            }
            FileProcessingFlowStep::ProcessVideoThumbnail => {
                self.0.handler.handle_process_video_thumbnail(instance).await?
            }
            FileProcessingFlowStep::StoreVideoThumbnail => {
                self.0.handler.handle_store_video_thumbnail(instance).await?
            }
            FileProcessingFlowStep::UpdateFileVideoThumbnail => {
                self.0.handler.handle_update_file_video_thumbnail(instance).await?
            }
            FileProcessingFlowStep::ProcessDocumentPreview => {
                self.0.handler.handle_process_document_preview(instance).await?
            }
            FileProcessingFlowStep::StoreDocumentPreview => {
                self.0.handler.handle_store_document_preview(instance).await?
            }
            FileProcessingFlowStep::UpdateFileDocumentPreview => {
                self.0.handler.handle_update_file_document_preview(instance).await?
            }
            FileProcessingFlowStep::ProcessCompression => {
                self.0.handler.handle_process_compression(instance).await?
            }
            FileProcessingFlowStep::StoreCompressedFile => {
                self.0.handler.handle_store_compressed_file(instance).await?
            }
            FileProcessingFlowStep::UpdateFileCompression => {
                self.0.handler.handle_update_file_compression(instance).await?
            }
            FileProcessingFlowStep::UpdateBucketCompressionStats => {
                self.0.handler.handle_update_bucket_compression_stats(instance).await?
            }
            FileProcessingFlowStep::ProcessVirusScan => {
                self.0.handler.handle_process_virus_scan(instance).await?
            }
            FileProcessingFlowStep::CheckThreatLevel => {
                let next = self.0.handler.evaluate_check_threat_level(instance).await?;
                Some(next)
            }
            FileProcessingFlowStep::UpdateScanSafe => {
                self.0.handler.handle_update_scan_safe(instance).await?
            }
            FileProcessingFlowStep::UpdateScanWarning => {
                self.0.handler.handle_update_scan_warning(instance).await?
            }
            FileProcessingFlowStep::NotifyScanWarning => {
                self.0.handler.handle_notify_scan_warning(instance).await?
            }
            FileProcessingFlowStep::UpdateScanThreat => {
                self.0.handler.handle_update_scan_threat(instance).await?
            }
            FileProcessingFlowStep::NotifyThreatDetected => {
                self.0.handler.handle_notify_threat_detected(instance).await?
            }
            FileProcessingFlowStep::ProcessDeduplication => {
                self.0.handler.handle_process_deduplication(instance).await?
            }
            FileProcessingFlowStep::CheckExistingHash => {
                self.0.handler.handle_check_existing_hash(instance).await?
            }
            FileProcessingFlowStep::UpdateExistingHash => {
                self.0.handler.handle_update_existing_hash(instance).await?
            }
            FileProcessingFlowStep::LinkFileHash => {
                self.0.handler.handle_link_file_hash(instance).await?
            }
            FileProcessingFlowStep::CreateNewHash => {
                self.0.handler.handle_create_new_hash(instance).await?
            }
            FileProcessingFlowStep::MarkComplete => {
                self.0.handler.handle_mark_complete(instance).await?
            }
            FileProcessingFlowStep::EmitCompleteEvent => {
                self.0.handler.handle_emit_complete_event(instance).await?
            }
            FileProcessingFlowStep::Complete => {
                self.0.handler.handle_complete(instance).await?;
                None // Terminal step
            }
            FileProcessingFlowStep::RetryOrFail => {
                let next = self.0.handler.evaluate_retry_or_fail(instance).await?;
                Some(next)
            }
            FileProcessingFlowStep::ScheduleRetry => {
                self.0.handler.handle_schedule_retry(instance).await?
            }
            FileProcessingFlowStep::RetryTerminal => {
                self.0.handler.handle_retry_terminal(instance).await?;
                None // Terminal step
            }
            FileProcessingFlowStep::MarkFailed => {
                self.0.handler.handle_mark_failed(instance).await?
            }
            FileProcessingFlowStep::EmitFailedEvent => {
                self.0.handler.handle_emit_failed_event(instance).await?
            }
            FileProcessingFlowStep::FailedTerminal => {
                self.0.handler.handle_failed_terminal(instance).await?;
                None // Terminal step
            }
            FileProcessingFlowStep::JobNotFound => {
                self.0.handler.handle_job_not_found(instance).await?;
                None // Terminal step
            }
            FileProcessingFlowStep::FileNotFound => {
                self.0.handler.handle_file_not_found(instance).await?;
                None // Terminal step
            }
            FileProcessingFlowStep::UnknownJobType => {
                self.0.handler.handle_unknown_job_type(instance).await?;
                None // Terminal step
            }
        };

        // Mark current step as completed
        instance.completed_steps.push(current_step);

        // Move to next step
        match next_step {
            Some(next) => {
                instance.current_step = Some(next);
            }
            None => {
                instance.current_step = None;
                instance.status = FlowStatus::Completed;
            }
        }

        instance.updated_at = chrono::Utc::now();
        Ok(())
    }

    /// Run the flow to completion
    pub async fn run(&self, instance: &mut FileProcessingFlowInstance) -> Result<(), FlowError> {
        while !instance.is_complete() && instance.status != FlowStatus::Waiting {
            self.execute_step(instance).await?;
        }
        Ok(())
    }

    /// Cancel the flow
    pub fn cancel(&self, instance: &mut FileProcessingFlowInstance) { self.0.cancel(instance) }

    /// Mark flow as failed
    pub fn fail(&self, instance: &mut FileProcessingFlowInstance, error: impl Into<String>) { self.0.fail(instance, error) }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_flow_instance_creation() {
        let instance = FileProcessingFlowInstance::new("test-1");
        assert_eq!(instance.id, "test-1");
        assert_eq!(instance.status, FlowStatus::Pending);
        assert!(!instance.is_complete());
    }

    #[test]
    fn test_flow_context() {
        let mut instance = FileProcessingFlowInstance::new("test-2");
        instance.set_context("key", serde_json::json!("value"));
        let value = instance.get_context("key");
        assert_eq!(value, Some(&serde_json::json!("value")));
    }

    #[test]
    fn test_flow_status_transitions() {
        let mut instance = FileProcessingFlowInstance::new("test-3");
        assert!(!instance.is_running());

        instance.status = FlowStatus::Running;
        assert!(instance.is_running());
        assert!(!instance.is_complete());

        instance.status = FlowStatus::Completed;
        assert!(instance.is_complete());
        assert!(!instance.is_running());
    }
}
