//! Use case type aliases for FileLock aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateFileLockDto, UpdateFileLockDto};
use crate::application::service::FileLockService;
use crate::domain::entity::FileLock;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateFileLockUseCase = CreateUseCase<FileLock, CreateFileLockDto, FileLockService>;
pub type UpdateFileLockUseCase = UpdateUseCase<FileLock, UpdateFileLockDto, FileLockService>;
pub type GetFileLockUseCase    = GetUseCase<FileLock, FileLockService>;
pub type DeleteFileLockUseCase = DeleteUseCase<FileLock, FileLockService>;
pub type ListFileLockUseCase   = ListUseCase<FileLock, FileLockService>;

// <<< CUSTOM
// END CUSTOM
