//! Use case type aliases for FileShare aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateFileShareDto, UpdateFileShareDto};
use crate::application::service::FileShareService;
use crate::domain::entity::FileShare;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateFileShareUseCase = CreateUseCase<FileShare, CreateFileShareDto, FileShareService>;
pub type UpdateFileShareUseCase = UpdateUseCase<FileShare, UpdateFileShareDto, FileShareService>;
pub type GetFileShareUseCase    = GetUseCase<FileShare, FileShareService>;
pub type DeleteFileShareUseCase = DeleteUseCase<FileShare, FileShareService>;
pub type ListFileShareUseCase   = ListUseCase<FileShare, FileShareService>;

// <<< CUSTOM
// END CUSTOM
