//! Get FileShare use case
//!
//! Generated by backbone-schema. Do not edit manually.

use std::sync::Arc;

use anyhow::{Result, anyhow};
use async_trait::async_trait;
use uuid::Uuid;

use super::UseCase;
use crate::domain::entity::FileShare;
use crate::infrastructure::persistence::FileShareRepository;

/// Input for getting a FileShare by ID
#[derive(Debug, Clone)]
pub struct GetFileShareInput {
    pub id: Uuid,
}

/// Output containing the FileShare
#[derive(Debug, Clone)]
pub struct GetFileShareOutput {
    pub file_share: FileShare,
}

/// Use case for getting a FileShare by ID
pub struct GetFileShareUseCase {
    repository: Arc<FileShareRepository>,
}

impl GetFileShareUseCase {
    pub fn new(repository: Arc<FileShareRepository>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl UseCase for GetFileShareUseCase {
    type Input = GetFileShareInput;
    type Output = GetFileShareOutput;

    async fn execute(&self, input: Self::Input) -> Result<Self::Output> {
        let entity = self.repository.find_by_id(input.id).await?
            .ok_or_else(|| anyhow!("FileShare not found"))?;

        Ok(GetFileShareOutput { file_share: entity })
    }
}
