//! List FileShare use case
//!
//! Generated by backbone-schema. Do not edit manually.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;

use super::UseCase;
use crate::domain::entity::FileShare;
use crate::infrastructure::persistence::FileShareRepository;
use backbone_orm::repository::PaginationParams;

/// Input for listing FileShares
#[derive(Debug, Clone, Default)]
pub struct ListFileShareInput {
    pub page: Option<u32>,
    pub per_page: Option<u32>,
    // <<< CUSTOM FILTERS START >>>
    // Add custom filter fields here
    // <<< CUSTOM FILTERS END >>>
}

/// Output containing list of FileShares
#[derive(Debug, Clone)]
pub struct ListFileShareOutput {
    pub file_shares: Vec<FileShare>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
    pub total_pages: u32,
}

/// Use case for listing FileShares with pagination
pub struct ListFileShareUseCase {
    repository: Arc<FileShareRepository>,
}

impl ListFileShareUseCase {
    pub fn new(repository: Arc<FileShareRepository>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl UseCase for ListFileShareUseCase {
    type Input = ListFileShareInput;
    type Output = ListFileShareOutput;

    async fn execute(&self, input: Self::Input) -> Result<Self::Output> {
        let page = input.page.unwrap_or(1);
        let per_page = input.per_page.unwrap_or(20);

        let pagination = PaginationParams::new(page, per_page);

        // <<< CUSTOM QUERY START >>>
        // Add custom query/filter logic here
        // <<< CUSTOM QUERY END >>>

        let result = self.repository.find_all(pagination).await?;

        let total_pages = ((result.total as f64) / (per_page as f64)).ceil() as u32;

        Ok(ListFileShareOutput {
            file_shares: result.items,
            total: result.total,
            page,
            per_page,
            total_pages,
        })
    }
}
