//! Use case type aliases for StoredFile aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateStoredFileDto, UpdateStoredFileDto};
use crate::application::service::StoredFileService;
use crate::domain::entity::StoredFile;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateStoredFileUseCase = CreateUseCase<StoredFile, CreateStoredFileDto, StoredFileService>;
pub type UpdateStoredFileUseCase = UpdateUseCase<StoredFile, UpdateStoredFileDto, StoredFileService>;
pub type GetStoredFileUseCase    = GetUseCase<StoredFile, StoredFileService>;
pub type DeleteStoredFileUseCase = DeleteUseCase<StoredFile, StoredFileService>;
pub type ListStoredFileUseCase   = ListUseCase<StoredFile, StoredFileService>;

// <<< CUSTOM
// END CUSTOM
